[FUEL_WARNING_0]
OBJECT_NAME=aim_fuel_warning
FUEL_SWITCH=7
EMISSIVE=145,0,0
DIFFUSE=0.3
INVERTED=0




;;;;  --- top leds of aim display, removed
[LED_0]
OBJECT_NAME=TOP_LED_RPM_0
RPM_SWITCH=5900
EMISSIVE=0,30,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_1]
OBJECT_NAME=TOP_LED_RPM_1
RPM_SWITCH=6000
EMISSIVE=0,30,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_2]
OBJECT_NAME=TOP_LED_RPM_2
RPM_SWITCH=6100
EMISSIVE=0,30,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_3]
OBJECT_NAME=TOP_LED_RPM_3
RPM_SWITCH=6200
EMISSIVE=50,20,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_4]
OBJECT_NAME=TOP_LED_RPM_4
RPM_SWITCH=6300
EMISSIVE=50,20,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_5]
OBJECT_NAME=TOP_LED_RPM_5
RPM_SWITCH=6400
EMISSIVE=50,20,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_6]
OBJECT_NAME=TOP_LED_RPM_6
RPM_SWITCH=6450
EMISSIVE=70,0,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_7]
OBJECT_NAME=TOP_LED_RPM_7
RPM_SWITCH=6500
EMISSIVE=70,0,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8

[LED_8]
OBJECT_NAME=TOP_LED_RPM_8
RPM_SWITCH=6600
EMISSIVE=70,0,0
DIFFUSE=0.3
BLINK_SWITCH=6600
BLINK_HZ=8