[HEADER] ; conor shanahan 2025 
;updated 03.13/2026

VERSION=10

[_EXTENSION]
PRACTICAL_TEMP_RATIO=0.9
USE_NEW_RR_SLIP=1
LATERAL_RAYS=3
LONGITUDINAL_RAYS=3
SMOOTH_LOAD_SENS=0
ENABLE_RAY_FORCE_WEIGHTING=0

[THERMAL_MODEL]
VERSION=2

[VIRTUALKM]
USE_LOAD=1

[EXPLOSION]
TEMPERATURE=650

[ADDITIONAL1]
BLANKETS_TEMP=80

[COMPOUND_DEFAULT]
INDEX=0

[FRONT]
NAME=Champiro SX2
SHORT_NAME=GTF
WIDTH=0.235
RADIUS=0.3179
RIM_RADIUS=0.2286
ANGULAR_INERTIA=1.750
DAMP=400
RATE=215000
CAMBER_SPRING_MULT=tire_camber_spring_k.lut
WEAR_CURVE=tire_wear.lut
SPEED_SENSITIVITY=0.001
RELAXATION_LENGTH=0.0705
ROLLING_RESISTANCE_0=14.5
ROLLING_RESISTANCE_1=0.00025
ROLLING_RESISTANCE_SLIP=800
CAMBER_GAIN=0.105
DCAMBER_0=1.0
DCAMBER_1=-8
DCAMBER_LUT=tire_camber_dy.lut
DCAMBER_LUT_SMOOTH=0
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=7.50
CX_MULT=1.17
FLEX_GAIN=-0.011
COMBINED_FACTOR=2.05
COMBINED_FACTOR_1=0.33
COMBINED_FACTOR_BRAKE_MULT=1.00
COMBINED_FACTOR_LOAD_K=0.0
BRAKE_DX_MOD=0.017
PRESSURE_STATIC=24.0
PRESSURE_SPRING_GAIN=8600
PRESSURE_FLEX_GAIN=-0.17
PRESSURE_RR_GAIN=0.60
PRESSURE_D_GAIN=0.0022
PRESSURE_IDEAL=31.0
FZ0=2800
LS_EXPY=0
LS_EXPX=0
DY_REF=0
DX_REF=0
DY_CURVE=sx2_lat.lut
DX_CURVE=sx2_long.lut
FALLOFF_LEVEL_CURVE=tire_heat_level.lut
FALLOFF_SPEED_CURVE=tire_heat_speed.lut
FALLOFF_LEVEL=0.730
FALLOFF_SPEED=11.0
DROPOFF_FACTOR_0=10.5
DROPOFF_FACTOR_1=1.00
FALLOFF_YSPEED_MULT=1.00
SAT_MULT=1.30
SAT_SPEED=1.45
SAT_PEAK_K=0.50
SAT_MULT_K=0.052
SAT_MIN_REF=-0.052
SAT_LOAD_K=-0.0000032
SIDEWALL_K_MULT=1.00
SIDEWALL_K_MULT_X=2.00
RADIUS_ANGULAR_K=0.010
RADIUS_ANGULAR_K_2=0.021
ROLLING_RADIUS_MULT=0.42
XMU=0.00
DY0=0.00
DY1=0.00
DX0=0.00
DX1=0.00
FLEX=0.00

[REAR]
NAME=Champiro SX2 RS
SHORT_NAME=GTR
WIDTH=0.278
RADIUS=0.3464
RIM_RADIUS=0.2286
ANGULAR_INERTIA=1.950
DAMP=440
RATE=250000
CAMBER_SPRING_MULT=tire_camber_spring_k.lut
WEAR_CURVE=tire_wear.lut
SPEED_SENSITIVITY=0.001
RELAXATION_LENGTH=0.0725
ROLLING_RESISTANCE_0=14.5
ROLLING_RESISTANCE_1=0.00025
ROLLING_RESISTANCE_SLIP=800
CAMBER_GAIN=0.105
DCAMBER_0=1.0
DCAMBER_1=-8
DCAMBER_LUT=tire_camber_dy.lut
DCAMBER_LUT_SMOOTH=0
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=7.80
CX_MULT=1.17
FLEX_GAIN=-0.013
COMBINED_FACTOR=1.95
COMBINED_FACTOR_1=0.36
COMBINED_FACTOR_BRAKE_MULT=1.00
COMBINED_FACTOR_LOAD_K=0.0
BRAKE_DX_MOD=0.019
PRESSURE_STATIC=26.0
PRESSURE_SPRING_GAIN=9000
PRESSURE_FLEX_GAIN=-0.17
PRESSURE_RR_GAIN=0.60
PRESSURE_D_GAIN=0.0022
PRESSURE_IDEAL=33.0
FZ0=3200
LS_EXPY=0
LS_EXPX=0
DY_REF=0
DX_REF=0
DY_CURVE=sx2rs_lat.lut
DX_CURVE=sx2rs_long.lut
FALLOFF_LEVEL_CURVE=tire_heat_level.lut
FALLOFF_SPEED_CURVE=tire_heat_speed.lut
FALLOFF_LEVEL=0.730
FALLOFF_SPEED=11.0
DROPOFF_FACTOR_0=10.5
DROPOFF_FACTOR_1=1.00
FALLOFF_YSPEED_MULT=1.00
SAT_MULT=1.30
SAT_SPEED=1.45
SAT_PEAK_K=0.50
SAT_MULT_K=0.052
SAT_MIN_REF=-0.052
SAT_LOAD_K=-0.0000032
SIDEWALL_K_MULT=1.00
SIDEWALL_K_MULT_X=2.00
RADIUS_ANGULAR_K=0.010
RADIUS_ANGULAR_K_2=0.021
ROLLING_RADIUS_MULT=0.42
XMU=0.00
DY0=0.00
DY1=0.00
DX0=0.00
DX1=0.00
FLEX=0.00

[THERMAL_FRONT]
SURFACE_TRANSFER=0.95
PATCH_TRANSFER=0.0021
CORE_TRANSFER=0.00011
INTERNAL_CORE_TRANSFER=0.0015
FRICTION_K=0.0070
ROLLING_K=0.11
PERFORMANCE_CURVE=tire_heat_mu.lut
GRAIN_GAMMA=1.2
GRAIN_GAIN=0.13
BLISTER_GAMMA=1.2
BLISTER_GAIN=0.13
COOL_FACTOR=3.2
SURFACE_ROLLING_K=0.027
TREAD_DEPTH=0.0060
BULK_HEIGHT=11.0
BEAD_WIDTH=14.0

[THERMAL_REAR]
SURFACE_TRANSFER=0.95
PATCH_TRANSFER=0.0021
CORE_TRANSFER=0.00011
INTERNAL_CORE_TRANSFER=0.0015
FRICTION_K=0.0075
ROLLING_K=0.11
PERFORMANCE_CURVE=tire_heat_mu.lut
GRAIN_GAMMA=1.2
GRAIN_GAIN=0.13
BLISTER_GAMMA=1.2
BLISTER_GAIN=0.13
COOL_FACTOR=3.2
SURFACE_ROLLING_K=0.025
TREAD_DEPTH=0.0060
BULK_HEIGHT=10.8
BEAD_WIDTH=14.5

[THERMAL2_FRONT]
CARCASS_ROLLING_K=0.117
SURFACE_TO_AMBIENT=0.0275
SURFACE_TO_CARCASS=0.0295
CARCASS_TO_SURFACE=0.153
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0013
CORE_TO_AMBIENT=0.0020
BRAKE_TO_CORE=0.000032
FRICTION_TEMP_K=1.02

[THERMAL2_REAR]
CARCASS_ROLLING_K=0.112
SURFACE_TO_AMBIENT=0.0305
SURFACE_TO_CARCASS=0.0325
CARCASS_TO_SURFACE=0.158
CARCASS_TO_CORE=0.0052
CORE_TO_CARCASS=0.0014
CORE_TO_AMBIENT=0.0020
BRAKE_TO_CORE=0.000032
FRICTION_TEMP_K=1.02