[HEADER]
VERSION=2

[_EXTENSION]
ENABLE=1
USE_ADVANCED_SYSTEM=1

[DATA]
MAX_TORQUE=1700
FRONT_SHARE=0.3
HANDBRAKE_TORQUE=1200	
COCKPIT_ADJUSTABLE=0
ADJUST_STEP=0

[DATA2]
MAX_PRESSURE_SUM=2604
PRESSURE_THRESHOLD_REAR=427
REDUCTION_RATIO_REAR=0.3
PEDAL_FORCE_LUT=brakes_booster.lut

[FRONT]
DISC_EFFECTIVE_RADIUS=0.1315
PISTON_DIAMETER_0=0.040 ;4pot
PISTON_DIAMETER_1=0.040
PISTON_DIAMETER_2=0.046
PISTON_DIAMETER_3=0.046

[REAR]
DISC_EFFECTIVE_RADIUS=0.127
PISTON_DIAMETER_0=0.04 ;2pot
PISTON_DIAMETER_1=0.04

[TEMPS_FRONT]
;294mm 7.3kg Vented
COOL_TRANSFER=0.00178
TORQUE_K=0.26517
COOL_SPEED_FACTOR_0=0.06518
CORE_TRANSFER_IN=0.0984
CORE_TRANSFER_OUT=0.3091
CORE_TRANSFER_AIR=0.0005
COOL_SPEED_FACTOR=0.000
DEFAULT_BLANKING=0
PERF_CURVE=brakes_mu_0_40.lut

[TEMPS_REAR]
;290mm 5.8kg Vented
COOL_TRANSFER=0.00154
TORQUE_K=0.30757
COOL_SPEED_FACTOR_0=0.06144
CORE_TRANSFER_IN=0.11842
CORE_TRANSFER_OUT=0.25989
CORE_TRANSFER_AIR=0.0005
COOL_SPEED_FACTOR=0.000
DEFAULT_BLANKING=0
PERF_CURVE=brakes_mu_0_40.lut