
[ITEM_0]
PARENT=INT_DATA_CENTER
POSITION=0.0011,-0.0052,0.000
TYPE=CLOCK
SIZE=0.011
COLOR=254,232,200,1
INTENSITY=2
VERSION=2
FONT=digital_mid
ALIGN=CENTER

[ITEM_1]
PARENT=INT_DATA_CENTER
POSITION=0.0011,-0.05,0.003
TYPE_EXT=AMBIENT_TEMP
INPUT=AMBIENT_TEMP
SIZE=0.01
COLOR=254,232,200,1
INTENSITY=2
VERSION=2
FONT=digital_mid
ALIGN=CENTER

[ITEM_2]
;odometer
PARENT=INT_DATA_CLUSTER
POSITION=-0.017,-0.0064,0.000
TYPE=PLACE_HOLDER
SIZE=0.01
COLOR=0,0,0,10
INTENSITY=2
VERSION=2
FONT=digital_mid
ALIGN=RIGHT

[ITEM_3]
;odometer text
PARENT=INT_DATA_CLUSTER
POSITION=-0.017,0.0005,0.000
TYPE=PLACE_HOLDER
TEXT=ODO
SIZE=0.006
COLOR=0,0,0,10
INTENSITY=2
VERSION=2
FONT=gallardo_1
ALIGN=RIGHT