[HEADER]
VERSION=3 ; emi v1.45

; 0.770 CdA  
; downforce	при 144км/ч		-20.05 kg | -14.95 kg

[WING_0]
NAME=FRONT
CHORD=0.50
SPAN=1.40
POSITION=0.000, -0.02, 1.77
LUT_AOA_CL=Aero_WING_Damage_Lift.lut
LUT_GH_CL=
CL_GAIN=750
LUT_AOA_CD=Aero_WING_Front_CD.lut
LUT_GH_CD=
CD_GAIN=750
ANGLE=0
ZONE_FRONT_CL=0.1    					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0.1    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

[WING_1]
NAME=CENTRE
CHORD=1.60
SPAN=1.55
POSITION=0.000, 0.19, -0.55
LUT_AOA_CL=Aero_WING_Centre_CD.lut
LUT_GH_CL=
CL_GAIN=0
LUT_AOA_CD=Aero_WING_Centre_CD.lut
LUT_GH_CD=
CD_GAIN=0.403
ANGLE=0
ZONE_FRONT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0.06     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0.06    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

[WING_2]
NAME=REAR
CHORD=0.50
SPAN=1.50
POSITION=0.000, 0.08, -2.4
LUT_AOA_CL=Aero_WING_Damage_Lift.lut
LUT_GH_CL=
CL_GAIN=1.333
LUT_AOA_CD=Aero_WING_Rear_CD.lut
LUT_GH_CD=
CD_GAIN=1.333
ANGLE=0
ZONE_FRONT_CL=0    						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0.1     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0.1    				 	; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0    					 	; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

;|||||||||||||||||Downforce||||||||||||||||||

[WING_3]
NAME=DNIWE_F							; name of the wing
CHORD=0.58								; length of the wing in meters
SPAN=1.2								; width of the wing in meters. both help determine the frontal area
POSITION=0, -0.375, 1.67						; position in x,y,z starting from the CoG
LUT_AOA_CL=Aero_Under_CL.lut		; Coefficient of Lift lookup table
LUT_GH_CL=Aero_Height_CL.lut		; Height aero lift multiplier lookup table
CL_GAIN=1.437						;Coefficient of Lift multiplier 
LUT_AOA_CD=                 		; Coefficient of drag lookup table
LUT_GH_CD=                  		; Height aero drag multiplier table
CD_GAIN=0 							; 0.5
ANGLE=0
ZONE_FRONT_CL=0.15    ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.150

[WING_4]
NAME=Rear Wing						; name of the wing
CHORD=0.22								; length of the wing in meters
SPAN=1.27								; width of the wing in meters. both help determine the frontal area
POSITION=0, 0.46, -2.45				; position in x,y,z starting from the CoG
LUT_AOA_CL=Aero_WING_Spoiler_CL.lut			; Coefficient of Lift lookup table
LUT_GH_CL=								; Height aero lift multiplier lookup table
CL_GAIN=3.579							; Coefficient of Lift multiplier 
LUT_AOA_CD=Aero_WING_Spoiler_CD.lut			; Coefficient of drag lookup table
LUT_GH_CD=         		; Height aero drag multiplier table
CD_GAIN=3.579							; Coefficient of drag multiplier (for easy fine tuning)
ANGLE=0
ZONE_FRONT_CL=0    ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0.15     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.150

;|||||||||||||||||SIDE||||||||||||||||||||

[FIN_0]
NAME=Side F
CHORD=1.570220
SPAN=0.761096
POSITION=0, -0.001174, 1.28772
LUT_AOA_CL=Aero_FIN_Front_CL.lut
LUT_GH_CL=
CL_GAIN=0.837
LUT_AOA_CD=Aero_FIN_Front_CD.lut
LUT_GH_CD=
CD_GAIN=0.837
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[FIN_1]
NAME=Side C
CHORD=1.570220
SPAN=1.167490
POSITION=0, 0.215569, -0.282504
LUT_AOA_CL=Aero_FIN_Centre_CL.lut
LUT_GH_CL=
CL_GAIN=0.545
LUT_AOA_CD=Aero_FIN_Centre_CD.lut
LUT_GH_CD=
CD_GAIN=0.545
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[FIN_2]
NAME=Side R
CHORD=1.570220
SPAN=0.808892
POSITION=0, 0.097219, -1.85272
LUT_AOA_CL=Aero_FIN_Rear_CL.lut
LUT_GH_CL=
CL_GAIN=0.787
LUT_AOA_CD=Aero_FIN_Rear_CD.lut
LUT_GH_CD=
CD_GAIN=0.787
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0