[HEADER]
VERSION=2

[_EXTENSION]
ENABLE=1
USE_ADVANCED_SYSTEM=1

[DATA]
MAX_TORQUE=3576			; Maximum Brake torque in Nm
FRONT_SHARE=0.5			; 0.694 Percentance of brake torque at front axis
HANDBRAKE_TORQUE=1300
COCKPIT_ADJUSTABLE=0   ; 0: no bias control from cockpit, 1: bias control from cockpit
ADJUST_STEP=0.5   ; step for bias cockpit adjustment.

[DATA2]
MAX_PRESSURE_SUM=2100

[FRONT]
DISC_EFFECTIVE_RADIUS=0.144
PISTON_DIAMETER_0=0.036
PISTON_DIAMETER_1=0.036
PISTON_DIAMETER_2=0.040
PISTON_DIAMETER_3=0.040

[REAR]
DISC_EFFECTIVE_RADIUS=0.127
PISTON_DIAMETER_0=0.038
PISTON_DIAMETER_1=0.038

[TEMPS_FRONT]
COOL_TRANSFER=0.0020
TORQUE_K=0.283
COOL_SPEED_FACTOR_0=0.103
COOL_SPEED_FACTOR=0.040
CORE_TRANSFER_IN=0.0394
CORE_TRANSFER_OUT=0.425
CORE_TRANSFER_AIR=0.00011
DEFAULT_BLANKING=0
PERF_CURVE=brakes_Type_A_pad_S.lut		
; PERF_CURVE=(|0=0.50|100=0.50|)

[TEMPS_REAR]
COOL_TRANSFER=0.0020
TORQUE_K=0.283
COOL_SPEED_FACTOR_0=0.094
COOL_SPEED_FACTOR=0.020
CORE_TRANSFER_IN=0.049
CORE_TRANSFER_OUT=0.343
CORE_TRANSFER_AIR=0.00011
DEFAULT_BLANKING=0
PERF_CURVE=brakes_Type_D_pad_F.lut
; PERF_CURVE=(|0=0.50|100=0.50|)

; Front	330	9.00	7	Type_B	S_Caliper	36	2	40	2
; Rear	296	5.70	2200	Type_D	S_Caliper	38	2	0	0

[DISCS_GRAPHICS]
DISC_LF=BRAKE_DISC_LF
DISC_RF=BRAKE_DISC_RF
DISC_LR=BRAKE_DISC_LR
DISC_RR=BRAKE_DISC_RR
FRONT_MAX_GLOW=10.0
REAR_MAX_GLOW=4.0
LAG_HOT=0.995
LAG_COOL=0.98