[HEADER]
VERSION=4

[_EXTENSION]
TORQUE_MODE_EX=2
FIX_PROGRESSIVE_RATE=1
DAMPER_LUTS=1


[BASIC]
WHEELBASE=2.573					; Wheelbase distance in meters
CG_LOCATION=0.6167				; Front Weight distribution in percentage

[ARB]
FRONT=50000						; Front antiroll bar stifness. in Nm
REAR=10000						; Rear antiroll bar stifness. in Nm


[FRONT]
TYPE=COSMIC
BASEY=-0.250							; Distance of CG from the center of the wheel in meters. Front Wheel Radius+BASEY=front CoG. Actual CG height =(FWR+FBasey)+(RWR+Rbasey))/CG_LOCATION%
TRACK=1.516								; Track width in meters (from pivot 3D placement of the 3d model of a wheel)						; push rod length in meters. positive raises ride height, negative lowers ride height.
HUB_MASS=48								; masse sospese anteriori

RIM_OFFSET=0

; Тела

BODY_0_NAME=F_SA95_StUp
BODY_0_MASS=0.6
BODY_0_INERTIA=0.050, 0.130, 0.050
BODY_0_POS=0.235, 0.473, -0.017
BODY_0_MIRROR=1

BODY_1_NAME=F_SA95_LCA
BODY_1_MASS=2
BODY_1_INERTIA=0.364, 0.030, 0.258
BODY_1_POS=0.224, -0.050, 0.011
BODY_1_MIRROR=1

; Верхнее соединение

DJ0=F_SA95_StKPin
DJ0_BODY_B=F_SA95_StUp
DJ0_POS0=1.19467,	0.195833,	-0.0235964
DJ0_POS1=0.2555, 0.539285, -0.0235964
DJ0_KP=1

DJ1=F_SA95_StCaster
DJ1_BODY_B=F_SA95_StUp
DJ1_POS0=0.237136,	0.48907,	-1.02217
DJ1_POS1=0.2555, 0.539285, -0.0235964

DJ2=F_SA91_StHeight
DJ2_BODY_B=F_SA95_StUp
DJ2_POS0=0.59846,	1.47711,	-0.077064
DJ2_POS1=0.2555, 0.539285, -0.0235964

SLIDER_0=F_SA95_Strut_SLIDER
SLIDER_0_BODY_A=F_SA95_StUp
SLIDER_0_POS0=0.244008, 0.507861, -0.0218049
SLIDER_0_POS1=0.0865426,	0.077271, 0.002744

; Нижнее соединение

J0=F_SA95_LCAF_bj
J0_BODY_B=F_SA95_LCA
J0_POS=0.398, -0.050, 0.140

J1=F_SA95_LCAR_bj
J1_BODY_B=F_SA95_LCA
J1_POS=0.398, -0.050, -0.120

J2=F_SA95_LCAM_bj
J2_BODY_A=F_SA95_LCA
J2_POS=0.040, -0.050, 0.010
J2_KP=0

STEER_JOINT_0=F_SA95_TOE
STEER_JOINT_0_POS0=0.398,	-0.010,	0.155
STEER_JOINT_0_POS1=0.020,	0.005,	0.135

TOE_OUT=0							; Toe-out expressed as the length of the steering arm in meters
STATIC_CAMBER=-0.81						; Static Camber in degrees. Actual camber relative to suspension geometry and movement, check values in game
STEER_JOINT_0_LENGTH_OFFSET=0.0003 ;Toe
DJ0_LENGTH_OFFSET=0.0020 ;Strut Camber
DJ1_LENGTH_OFFSET=-0.0010 ;Strut Caster

[FRONT_COILOVER_0] ;Corner spring
PULL_FORCE=0
PRELOAD_FORCE=7300
PRELOAD=0
FLIP_PRELOAD=0

;BODY_A=
BODY_B=F_SA95_LCA
POS0=0.261, 0.180, 0.029
POS1=0.211,	-0.064, 0.029

MIN_LENGTH=0.150
MAX_LENGTH=0.340
BUMPSTOP_GAP=0.400

INSTALL_RATE=1400000
RATE=240000

[FRONT_COILOVER_1] ;Corner damper
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=0
PRELOAD=0
FLIP_PRELOAD=0

BODY_A=F_SA95_StUp
;BODY_B=HUB_L
POS0=0.244008, 0.507861, -0.0218049
POS1=0.0865426,	0.077271, 0.002744

MIN_LENGTH=0.400; 70mm
MAX_LENGTH=0.520
BUMPSTOP_GAP=0.025; 45mm

INSTALL_RATE=900000
RATE=0

[FRONT_SPRING_0] ;BUSHING SPRING
POS_A=0, 1, 0
POS_B=0, 0, 0
PRELOAD=0.000

RATE=1500

[FRONT_DAMPER_0] ;BUSHING DAMPER
POS_A=0, 1, 0
POS_B=0, 0, 0

DAMP_BUMP=120	
DAMP_FAST_BUMP=120	
DAMP_FAST_BUMPTHRESHOLD=1	
DAMP_REBOUND=120	
DAMP_FAST_REBOUND=120	
DAMP_FAST_REBOUNDTHRESHOLD=1	

[REAR]
TYPE=COSMIC
BASEY=-0.250
TRACK=1.516
HUB_MASS=59
RIM_OFFSET=-0.020

BODY_0_NAME=R_SA95_LCA
BODY_0_MASS=7	
BODY_0_INERTIA=0.468, 0.050, 0.400
BODY_0_POS=0.346, -0.099, 0.052
BODY_0_MIRROR=1

; Верхнее соединение

DJ0=R_SA95_UCAF
DJ0_POS0=0.44019,	0.150,	0.094
DJ0_POS1=0.120, 0.160, -0.005
DJ0_KP=1

DJ1=R_SA95_UCAR
DJ1_POS0=0.41819,	0.150,	-0.099
DJ1_POS1=0.120, 0.160, -0.005

; Нижнее соединение

J0=R_SA95_LCAF_bj
J0_BODY_B=R_SA95_LCA
J0_POS=0.54019 , -0.080, 0.294

J1=R_SA95_LCAR_bj
J1_BODY_B=R_SA95_LCA
J1_POS=0.57019, -0.080, -0.187 

J2=R_SA95_LCAM_bj
J2_BODY_A=R_SA95_LCA
J2_POS=0.110, -0.110, 0.005
J2_KP=0

STEER_JOINT_0=R_SA95_TOE
STEER_JOINT_0_POS0=0.55069,	-0.011,	-0.108
STEER_JOINT_0_POS1=0.115,	-0.031,	-0.100

TOE_OUT=-0.00							; Toe-out expressed as the length of the steering arm in meters
STATIC_CAMBER=-0.81						; Static Camber in degrees. Actual camber relative to suspension geometry and movement, check values in game
STEER_JOINT_0_LENGTH_OFFSET=0.0001 ;Toe
;DJ3_LENGTH_OFFSET=-0.0060 ;Exc Camber

[REAR_COILOVER_0] ;Corner spring
PULL_FORCE=0
PRELOAD_FORCE=3600
PRELOAD=0

BODY_B=R_SA95_LCA
POS0=0.267 , 0.215, 0.192
POS1=0.267 , -0.108, 0.192

MIN_LENGTH=0.100
MAX_LENGTH=0.600
BUMPSTOP_GAP=0.400

INSTALL_RATE=1400000
RATE=180000

[REAR_COILOVER_1] ;Corner damper
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=0
PRELOAD=0

BODY_B=R_SA95_LCA
POS0=0.247 , 0.622, -0.102 
POS1=0.247 , -0.104, -0.082

MIN_LENGTH=0.670; n=726mm
MAX_LENGTH=0.790
BUMPSTOP_GAP=0.021; 61mm

INSTALL_RATE=900000
RATE=0

[REAR_SPRING_0] ;BUSHING SPRING
POS_A=0, 1, 0
POS_B=0, 0, 0
PRELOAD=0.000

RATE=3000

[REAR_DAMPER_0] ;BUSHING DAMPER
POS_A=0, 1, 0
POS_B=0, 0, 0
DAMP_BUMP=240	
DAMP_FAST_BUMP=240	
DAMP_FAST_BUMPTHRESHOLD=1	
DAMP_REBOUND=240	
DAMP_FAST_REBOUND=240	
DAMP_FAST_REBOUNDTHRESHOLD=1	

[GRAPHICS_OFFSETS]
WHEEL_LF=0.02								;Left front graphical offset of the wheel positioning in the x axis (width). + is left - is right movement
SUSP_LF=0.02								;Left front graphical offset of the suspension positioning in the x axis (width). + is left - is right movement
WHEEL_RF=-0.02								; Right front as above
SUSP_RF=-0.02									; Right front as above
WHEEL_LR=0.04								; Left rear as above
SUSP_LR=0.04								; Left rear as above
WHEEL_RR=-0.04								; Right rear as above
SUSP_RR=-0.04								; Right rear as above

[DAMAGE]
MIN_VELOCITY=40				; MINUMUM VELOCITY TO START TAKING DAMAGE
GAIN=0.0004					; AMOUNT OF STEER ROD DEFLECTION FOR IMPACT KMH
MAX_DAMAGE=0.05			; MAXIMUM AMOUNT OF STEER ROD DEFLECTION ALLOWED
DEBUG_LOG=1					; ACTIVATES DAMAGE DEBUG IN THE LOG
