[HEADER]
VERSION=10 ; emi 2.15
; Built by Ini-F calculator, hope you like it :)

[_EXTENSION]
USE_NEW_RR_SLIP=1
MAX_RAY_ANGLE=60
LATERAL_RAYS=1
LONGITUDINAL_RAYS=1

[THERMAL_MODEL]
VERSION=2

[VIRTUALKM]
USE_LOAD=1

[EXPLOSION]
TEMPERATURE=300

[ADDITIONAL1]
BLANKETS_TEMP=40

[COMPOUND_DEFAULT]
INDEX=1

[FRONT]
NAME=Bridgestone Potenza Sport
SHORT_NAME=PtzS
TYPE_HINT=TREADED
WIDTH=0.26   ;0.275-0.015  /40
RADIUS=0.3388
RIM_RADIUS=0.2479      ;18R+1.5
ANGULAR_INERTIA=1.6565    ;R9.35kg  T11.75kg  D9kg, 330mm
DAMP=889
RATE=402568
CAMBER_SPRING_MULT=tire_camber_spring_k_275.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_40.lut
SPEED_SENSITIVITY=0.00102
RELAXATION_LENGTH=0.053
ROLLING_RESISTANCE_0=11
ROLLING_RESISTANCE_1=0.002155
ROLLING_RESISTANCE_SLIP=817

CAMBER_GAIN=0.115
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_6deg.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=6.29
CX_MULT=1.10
BRAKE_DX_MOD=-0.02

PRESSURE_STATIC=44
PRESSURE_SPRING_GAIN=8922
PRESSURE_FLEX_GAIN=-0.25
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=50.5
; F500.24kg | R358.62kg   1717.71kg / 58.24%
FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5  ;   FZ0_MU   | FZ0_GRIP  
DX_REF=0.5   ;  SLOPE Y   | SLOPE X  
DY_REF=0.5      ; не используется
DX_CURVE=tire_PtzS_275_DX.lut
DY_CURVE=tire_PtzS_275_DY.lut
FLEX_GAIN=0.06

FALLOFF_LEVEL_CURVE=tire_heat_road_70_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_70_speed.lut
FALLOFF_LEVEL=0.81
FALLOFF_SPEED=13
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_FRONT]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_70_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_FRONT]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000305
SURFACE_TO_AMBIENT=0.0303
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
; FLEX_SPEED_COEFF=0.5
FRICTION_TEMP_K=1

[REAR]
NAME=Bridgestone Potenza Sport
SHORT_NAME=PtzS
TYPE_HINT=TREADED
WIDTH=0.29   ;0.305-0.015  /35
RADIUS=0.3355
RIM_RADIUS=0.2479      ;18R+1.5
ANGULAR_INERTIA=1.6349    ;R10.1kg  T12.2kg  D5.7kg, 296mm
DAMP=861
RATE=300749
CAMBER_SPRING_MULT=tire_camber_spring_k_305.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_40.lut
SPEED_SENSITIVITY=0.0009
RELAXATION_LENGTH=0.044
ROLLING_RESISTANCE_0=11
ROLLING_RESISTANCE_1=0.002507
ROLLING_RESISTANCE_SLIP=832

CAMBER_GAIN=0.12
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_6deg.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=6.02
CX_MULT=1.10
BRAKE_DX_MOD=-0.02

PRESSURE_STATIC=31
PRESSURE_SPRING_GAIN=9379
PRESSURE_FLEX_GAIN=-0.25
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=36

FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5  ;   FZ0_MU   | FZ0_GRIP  
DX_REF=0.5   ;  SLOPE Y   | SLOPE X  
DY_REF=0.5      ; не используется
DX_CURVE=tire_PtzS_305_DX.lut
DY_CURVE=tire_PtzS_305_DY.lut
FLEX_GAIN=0.05

FALLOFF_LEVEL_CURVE=tire_heat_road_70_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_70_speed.lut
FALLOFF_LEVEL=0.81
FALLOFF_SPEED=13
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_REAR]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0074
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_70_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_REAR]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000274
SURFACE_TO_AMBIENT=0.0336
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
; FLEX_SPEED_COEFF=0.5
FRICTION_TEMP_K=1

[FRONT_1]
NAME=Yokohama ADVAN Neova
SHORT_NAME=AD09
TYPE_HINT=RACING_TREADED
WIDTH=0.26   ;0.275-0.015  /40
RADIUS=0.3388
RIM_RADIUS=0.2479      ;18R+1.5
ANGULAR_INERTIA=1.6565    ;R9.35kg  T11.75kg  D9kg, 330mm
DAMP=889
RATE=402568
CAMBER_SPRING_MULT=tire_camber_spring_k_275.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_40.lut
SPEED_SENSITIVITY=0.00102
RELAXATION_LENGTH=0.053
ROLLING_RESISTANCE_0=15
ROLLING_RESISTANCE_1=0.002155
ROLLING_RESISTANCE_SLIP=817

CAMBER_GAIN=0.115
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_6deg.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=6.79
CX_MULT=1.10
BRAKE_DX_MOD=-0.02

PRESSURE_STATIC=44
PRESSURE_SPRING_GAIN=8922
PRESSURE_FLEX_GAIN=-0.25
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=50.5
; F500.24kg | R358.62kg   1717.71kg / 58.24%
FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_AD09_275_DX.lut
DY_CURVE=tire_AD09_275_DY.lut
FLEX_GAIN=0.06

FALLOFF_LEVEL_CURVE=tire_heat_road_75_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_75_speed.lut
FALLOFF_LEVEL=0.81
FALLOFF_SPEED=13
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_FRONT_1]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_75_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_FRONT_1]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000305
SURFACE_TO_AMBIENT=0.0303
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
; FLEX_SPEED_COEFF=0.5
FRICTION_TEMP_K=1

[REAR_1]
NAME=Yokohama ADVAN Neova
SHORT_NAME=AD09
TYPE_HINT=RACING_TREADED
WIDTH=0.29   ;0.305-0.015  /35
RADIUS=0.3355
RIM_RADIUS=0.2479      ;18R+1.5
ANGULAR_INERTIA=1.6349    ;R10.1kg  T12.2kg  D5.7kg, 296mm
DAMP=861
RATE=300749
CAMBER_SPRING_MULT=tire_camber_spring_k_305.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_40.lut
SPEED_SENSITIVITY=0.0009
RELAXATION_LENGTH=0.044
ROLLING_RESISTANCE_0=15
ROLLING_RESISTANCE_1=0.002507
ROLLING_RESISTANCE_SLIP=832

CAMBER_GAIN=0.12
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_6deg.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=6.52
CX_MULT=1.10
BRAKE_DX_MOD=-0.02

PRESSURE_STATIC=31
PRESSURE_SPRING_GAIN=9379
PRESSURE_FLEX_GAIN=-0.25
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=36

FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_AD09_305_DX.lut
DY_CURVE=tire_AD09_305_DY.lut
FLEX_GAIN=0.05

FALLOFF_LEVEL_CURVE=tire_heat_road_75_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_75_speed.lut
FALLOFF_LEVEL=0.81
FALLOFF_SPEED=13
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_REAR_1]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_75_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_REAR_1]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000274
SURFACE_TO_AMBIENT=0.0336
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
; FLEX_SPEED_COEFF=0.5
FRICTION_TEMP_K=1