[HEADER]
VERSION=2

[BRAKE_0]
NAME=TL_GR86_BRAKE
COLOR=50,0.0,0.0
OFF_COLOR=42,0.0,0.0

[BRAKE_1]
NAME=CENTRAL_light
COLOR=300.0,0.0,0.0
OFF_COLOR=0.0,0.0,0.0

[BRAKE_2]
NAME=RearLight_1
COLOR=15,0.0,0.0
OFF_COLOR=6,0.0,0.0

[LIGHT_0]
NAME=HL_GR86_FRONTLIFHT_DRL
COLOR=550 , 550 ,550
OFF_COLOR=550 , 550 ,550

[LIGHT_1]
NAME=INT_display_A
COLOR=1.5,1.5,4

[LIGHT_2]
NAME=HL_GR86_FRONTLIGHT_0_BULB
COLOR=1800,1800,1800
OFF_COLOR=100,100,100

[LIGHT_3]
NAME=HL_GR86_FRONTLIGHT_0_BEAM
COLOR=250,250,250
OFF_COLOR=5,5,5

[LIGHT_4]
NAME=HL_GR86_FRONTLIGHT_1_BULB
COLOR=1800,1800,1800

[LIGHT_5]
NAME=HL_GR86_FRONTLIGHT_1_BEAM
COLOR=250,250,250

[LIGHT_6]
NAME=brz_ledstripheadlight1
COLOR=35,35,35


[LIGHT_7]
;NAME=data-display.002
COLOR=10.35,10.35,10.35
OFF_COLOR=4.65,4.65,4.65

[LIGHT_8]
;NAME=buttonms
COLOR=10.35,10.35,10.35
OFF_COLOR=2.65,2.65,2.65





[BRAKE_3]
NAME=EXT_LED_STRIP_BRAKE_F.001_SUB0
COLOR=1200,0,0

[BRAKE_4]
NAME=EXT_LED_STRIP_BRAKE_F_pad.001
COLOR=0.5,0,0

[BRAKE_5]
NAME=EXT_LED_STRIP_BRAKE_F_SUB1
COLOR=1200,3,3

[BRAKE_6]
NAME=EXT_LED_STRIP_BRAKE_R_SUB1
COLOR=1200,3,3
