[DISPLAY_METHOD]

SHOW_CLICKS=1

[GEARS]
USE_GEARSET=2



/////////////////////////////////////////////////////

;TYRES

/////////////////////////////////////////////////////



[PRESSURE_LF]
SHOW_CLICKS=0
TAB=TYRES
NAME=Pressure LF
MIN=15
MAX=40
STEP=1
POS_X=0
POS_Y=2
HELP=HELP_LF_PRESSURE



[PRESSURE_RF]
SHOW_CLICKS=0
TAB=TYRES
NAME=Pressure RF
MIN=15
MAX=40
STEP=1
POS_X=1
POS_Y=2
HELP=HELP_RF_PRESSURE



[PRESSURE_LR]
SHOW_CLICKS=0
TAB=TYRES
NAME=Pressure LR
MIN=15
MAX=40
STEP=1
POS_X=0
POS_Y=4
HELP=HELP_LR_PRESSURE



[PRESSURE_RR]
SHOW_CLICKS=0
TAB=TYRES
NAME=Pressure RR
MIN=15
MAX=40
STEP=1
POS_X=1
POS_Y=4
HELP=HELP_RR_PRESSURE

/////////////////////////////////////////////////////
;ALIGNMENT
/////////////////////////////////////////////////////

[CAMBER_LF]
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=CAMBER_LF
MIN=-0.8	;degrees min
MAX=0.2	;degrees max
STEP=1 		;step is in degrees / 10
POS_X=0
POS_Y=0
HELP=HELP_LF_CAMBER

[CAMBER_RF]
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=CAMBER_RF
MIN=-0.8	;degrees min
MAX=0.2	;degrees max
STEP=1		;step is in degrees / 10
POS_X=1
POS_Y=0
HELP=HELP_RF_CAMBER

[TOE_OUT_LF]
SHOW_CLICKS=2
TAB=ALIGNMENT
NAME=Toe LF
MIN=-20
MAX=35
STEP=2
POS_X=0
POS_Y=1
HELP=HELP_LF_TOE

[TOE_OUT_RF]
SHOW_CLICKS=2
TAB=ALIGNMENT
NAME=Toe RF
MIN=-20
MAX=35
STEP=2
POS_X=1
POS_Y=1
HELP=HELP_RF_TOE

[DJ2_LENGTH_OFFSET_LR] ;works for any distance joint. Adjust length via setup, 0 is design length.
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=Toe LR
MIN=-23 ;0.1mm
MAX=-3  ;0.1mm
STEP=1   ;0.1mm
POS_X=0
POS_Y=6
DJ2_LENGTH_OFFSET=-13
HELP=NULL

[DJ2_LENGTH_OFFSET_RR] ;works for any distance joint. Adjust length via setup, 0 is design length.
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=Toe RR
MIN=-23 ;0.1mm
MAX=-3  ;0.1mm
STEP=1   ;0.1mm
POS_X=1
POS_Y=6
DJ2_LENGTH_OFFSET=-13
HELP=NULL

[CAMBER_LR]
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=CAMBER_LR
MIN=-1.2
MAX=-0.2
STEP=1
POS_X=0
POS_Y=5
HELP=HELP_LR_CAMBER

[CAMBER_RR]
SHOW_CLICKS=0
TAB=ALIGNMENT
NAME=CAMBER_RR
MIN=-1.2
MAX=-0.2
STEP=1
POS_X=1
POS_Y=5
HELP=HELP_LR_CAMBER


/////////////////////////////////////////////////////

;GENERIC

/////////////////////////////////////////////////////



[FUEL]

SHOW_CLICKS=0
TAB=GENERIC
NAME=Fuel
MIN=5
MAX=80
STEP=1
POS_X=0.5
POS_Y=0
HELP=HELP_FUEL

