[HEADER]
VERSION=4

[_EXTENSION]
TORQUE_MODE_EX=2
DAMPER_LUTS=1
	
[BASIC]
WHEELBASE=2.43			
CG_LOCATION=0.52					

[ARB]
FRONT=16000							
REAR=3000								


[FRONT]
TYPE=COSMIC
BASEY=-0.18
TRACK=1.53
HUB_MASS=48.6225
RIM_OFFSET=0.04

DJ0=FC_LCA_FRONT
DJ0_BODY_A=FC_FLCA_PICKUP
DJ0_BODY_B=HUB_L
DJ0_POS_A=0.395, -0.09, 0.02
DJ0_POS_B=0.0975, -0.105, 0

DJ1=FC_LCA_REAR
DJ1_BODY_A=FC_RLCA_PICKUP
DJ1_BODY_B=HUB_L
DJ1_POS_A=0.395, -0.09, -0.34
DJ1_POS_B=0.0975, -0.105, 0
DJ1_KP=0

J0=FC_STRUT_TOP
J0_BODY_A=CHASSIS
J0_BODY_B=FC_STRUT_BODY
J0_POS=0.235, 0.455, -0.0475
J0_KP=1

STEER_JOINT_0=FC_TOE
STEER_JOINT_0_BODY_A=CHASSIS
STEER_JOINT_0_BODY_B=HUB_L
STEER_JOINT_0_POS_A=0.43, -0.06, 0.0875
STEER_JOINT_0_POS_B=0.0925, -0.0675, 0.12

BODY_0_NAME=FC_STRUT_BODY
BODY_0_MASS=1
BODY_0_INERTIA=0.1, 0.1, 0.1
BODY_0_POS=0.235, 0.455, -0.0475
BODY_0_MIRROR=1

SLIDER_0=FC_STRUT_SLIDER
SLIDER_0_BODY_A=FC_STRUT_BODY
SLIDER_0_BODY_B=HUB_L
SLIDER_0_POS_A=0.235, 0.455, -0.0475
SLIDER_0_POS_B=0.12, 0.05, 0.0
SLIDER_0_PARITY=-1

;FC Front Adjusters

BODY_1_NAME=FC_FLCA_PICKUP
BODY_1_MASS=1
BODY_1_INERTIA=0.1, 0.1, 0.1
BODY_1_POS=0.395, -0.09, 0.02
BODY_1_MIRROR=1

SLIDER_1=FC_FLCA_SLIDER
SLIDER_1_BODY_A=CHASSIS
SLIDER_1_BODY_B=FC_FLCA_PICKUP
SLIDER_1_POS0=0.495, -0.09, 0.02
SLIDER_1_POS1=0.395, -0.09, 0.02
SLIDER_1_PARITY=-1

DJ2=FC_FLCA_ADJUSTER
DJ2_BODY_A=CHASSIS
DJ2_BODY_B=FC_FLCA_PICKUP
DJ2_POS0=0.495, -0.09, 0.02
DJ2_POS1=0.395, -0.09, 0.02

BODY_2_NAME=FC_RLCA_PICKUP
BODY_2_MASS=1
BODY_2_INERTIA=0.1, 0.1, 0.1
BODY_2_POS=0.395, -0.09, -0.34
BODY_2_MIRROR=1

SLIDER_2=FC_RLCA_SLIDER
SLIDER_2_BODY_A=CHASSIS
SLIDER_2_BODY_B=FC_RLCA_PICKUP
SLIDER_2_POS0=0.495, -0.09, -0.34
SLIDER_2_POS1=0.395, -0.09, -0.34
SLIDER_2_PARITY=-1

DJ3=FC_RLCA_ADJUSTER
DJ3_BODY_A=CHASSIS
DJ3_BODY_B=FC_RLCA_PICKUP
DJ3_POS0=0.495, -0.09, -0.34
DJ3_POS1=0.395, -0.09, -0.34


TOE_OUT=0.00000 
STATIC_CAMBER=-0.33
STEER_JOINT_0_LENGTH_OFFSET=0.0000 


[FRONT_COILOVER_0] ;Corner spring
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=3100
PRELOAD=0
BODY_A=FC_STRUT_BODY
BODY_B=HUB_L
POS_A=0.235, 0.455, -0.0475
POS_B=0.135, 0.05, 0.0
MIN_LENGTH=0.32
MAX_LENGTH=0.52
BUMPSTOP_GAP=0.045
INSTALL_RATE=500000
RATE=23000 ; calculated by SwitchPro3
DAMP_BUMP=7000					 ; Damper wheel rate stiffness in N sec/m in slow speed compression
DAMP_FAST_BUMP=10000				 ; Damper wheel rate stiffness in N sec/m in fast speed compression
DAMP_FAST_BUMPTHRESHOLD=0.09			 ; Damper bump slow/fast threshold in seconds
DAMP_REBOUND=8000				 ; Damper wheel rate stiffness in N sec/m in slow speed rebound
DAMP_FAST_REBOUND=12000			 ; Damper wheel rate stiffness in N sec/m in fast speed rebound
DAMP_FAST_REBOUNDTHRESHOLD=0.11

[REAR]
TYPE=COSMIC
BASEY=-0.20
TRACK=1.52
ROD_LENGTH=0.065
HUB_MASS=50
RIM_OFFSET=0.04

DJ0=FC_CAMBER_LINKAGE
DJ0_POS_A=0.50, -0.03, 0.30
DJ0_POS_B=0.50, -0.09, 0.30
DJ0_BODY_B=FC_TRAILING_ARM

DJ1=FC_LCA
DJ1_POS_A=0.64, -0.01, 0.25
DJ1_POS_B=0.22, 0.01, 0.05
DJ1_BODY_B=FC_TRAILING_ARM

J0=FC_TRAILING_ARM_CHASSIS
J0_BODY_A=FC_TRAILING_ARM_CHASSIS_BUSHING
J0_BODY_B=FC_TRAILING_ARM
J0_POS=0.18, -0.03, 0.42

J1=FC_TRAILING_UPPER
J1_BODY_A=FC_TRAILING_ARM
J1_BODY_B=HUB_L
J1_POS=0.15, 0.10, -0.066
J1_KP=1

J2=FC_TRAILING_LOWER
J2_BODY_A=FC_TRAILING_ARM
J2_BODY_B=HUB_L
J2_POS=0.08, -0.10, -0.06
J2_KP=0 

J3=FC_TRAILING_ARM_FRONT
J3_BODY_A=FC_TRAILING_ARM
J3_BODY_B=HUB_L
J3_POS=0.095, -0.05, 0.07

BODY_0_NAME=FC_TRAILING_ARM
BODY_0_MASS=1
BODY_0_INERTIA=0.1, 0.1, 0.1
BODY_0_POS=0.2125, -0.0275, 0.20	
BODY_0_MIRROR=1

BODY_1_NAME=FC_TRAILING_ARM_CHASSIS_BUSHING
BODY_1_MASS=1
BODY_1_INERTIA=0.1, 0.1, 0.1
BODY_1_POS=0.18, -0.03, 0.42
BODY_1_MIRROR=1

SLIDER_0=FC_TRAILING_ARM_CHASSIS_BUSHING_SLIDER
SLIDER_0_BODY_A=CHASSIS
SLIDER_0_BODY_B=FC_TRAILING_ARM_CHASSIS_BUSHING
SLIDER_0_POS0=0.28, -0.03, 0.42
SLIDER_0_POS1=0.18, -0.03, 0.42

DJ2=FC_TRAILING_ARM_CHASSIS_BUSHING_ADJUSTER
DJ2_BODY_A=CHASSIS
DJ2_BODY_B=FC_TRAILING_ARM_CHASSIS_BUSHING
DJ2_POS0=0.28, -0.03, 0.42
DJ2_POS1=0.18, -0.03, 0.42


TOE_OUT=-0.00010
STATIC_CAMBER=-0.7
DJ2_LENGTH_OFFSET=-0.0013

[REAR_COILOVER_0]
PULL_FORCE=0			
RATE=26000 ;thanks SwitchPro3 for calculating			
PRELOAD=0			
PRELOAD_FORCE=2900	
POS0=0.26, 0.44, -0.1125
POS1=0.23, -0.08, -0.0575
BODY_A=CHASSIS
BODY_B=HUB_L
MIN_LENGTH=0.40	      
MAX_LENGTH=0.575		       
END_RATE=250000			
END_VTAPER=0.02			
END_VMAX=0.10			
BUMPSTOP_GAP=0.048             
ELECT_LOG=CORNER             
DAMP_BUMP=5600
DAMP_FAST_BUMP=7800
DAMP_FAST_BUMPTHRESHOLD=0.09
DAMP_REBOUND=6800
DAMP_FAST_REBOUND=9000
DAMP_FAST_REBOUNDTHRESHOLD=0.11

[GRAPHICS_OFFSETS]
WHEEL_LF=0.0					;Left front graphical offset of the wheel positioning in the x axis (width). + is left - is right movement
SUSP_LF=-0.0					;Left front graphical offset of the suspension positioning in the x axis (width). + is left - is right movement
WHEEL_RF=-0.0					; Right front as above
SUSP_RF=0.0				; Right front as above
WHEEL_LR=0.0				; Left rear as above
SUSP_LR=-0.0					; Left rear as above
WHEEL_RR=-0.0					; Right rear as above
SUSP_RR=0.0			; Right rear as above

[DAMAGE]
MIN_VELOCITY=40				; MINUMUM VELOCITY TO START TAKING DAMAGE
GAIN=0.0004					; AMOUNT OF STEER ROD DEFLECTION FOR IMPACT KMH
MAX_DAMAGE=0.05			; MAXIMUM AMOUNT OF STEER ROD DEFLECTION ALLOWED
DEBUG_LOG=1					; ACTIVATES DAMAGE DEBUG IN THE LOG

