[HEADER]
VERSION=2

[_EXTENSION]
TORQUE_MODE_EX=2
	
[BASIC]
WHEELBASE=2.952				; Wheelbase distance in meters
CG_LOCATION=0.583						; Front Weight distribution in percentance

[ARB]
FRONT=5000							; Front antiroll bar stifness. in Nm
REAR=0								; Rear antiroll bar stifness. in Nm


[FRONT]
TYPE=COSMIC
BASEY=-0.280
TRACK=1.560
HUB_MASS=37
RIM_OFFSET=0.050

DJ0=CHARGER_UCA_FRONT
DJ0_BODY_A=CHASSIS
DJ0_BODY_B=HUB_L
DJ0_POS0=0.35, 0.16, 0.0900
DJ0_POS1=0.147, 0.13, 0.005

DJ1=CHARGER_UCA_REAR
DJ1_BODY_A=CHASSIS
DJ1_BODY_B=HUB_L
DJ1_POS0=0.35, 0.145, -0.09
DJ1_POS1=0.147, 0.13, 0.005
DJ1_KP=1

DJ2=CHARGER_LCA_FRONT
DJ2_BODY_A=CHARGER_FLCA_PICKUP
DJ2_BODY_B=HUB_L
DJ2_POS0=0.45, -0.03, 0.02
DJ2_POS1=0.115, -0.10, 0.0

DJ3=CHARGER_LCA_REAR
DJ3_BODY_A=CHARGER_RLCA_PICKUP
DJ3_BODY_B=HUB_L
DJ3_POS0=0.45, -0.03, -0.02
DJ3_POS1=0.115, -0.10, 0.0
DJ3_KP=0

STEER_JOINT_0=CHARGER_TOE
STEER_JOINT_0_BODY_A=CHASSIS
STEER_JOINT_0_BODY_B=HUB_L
STEER_JOINT_0_POS0=0.47, -0.07, -0.17
STEER_JOINT_0_POS1=0.127, -0.12, -0.18

;Charger Front Adjusters

BODY_0_NAME=CHARGER_FLCA_PICKUP
BODY_0_MASS=1
BODY_0_INERTIA=0.1, 0.1, 0.1
BODY_0_POS=0.45, -0.03, 0.02
BODY_0_MIRROR=1

SLIDER_0=CHARGER_FLCA_SLIDER
SLIDER_0_BODY_A=CHASSIS
SLIDER_0_BODY_B=CHARGER_FLCA_PICKUP
SLIDER_0_POS0=0.52, -0.03, 0.02
SLIDER_0_POS1=0.45, -0.03, 0.02
SLIDER_0_PARITY=-1

DJ4=CHARGER_FLCA_ADJUSTER
DJ4_BODY_A=CHASSIS
DJ4_BODY_B=CHARGER_FLCA_PICKUP
DJ4_POS0=0.55, -0.03, 0.0200
DJ4_POS1=0.45, -0.03, 0.02

BODY_1_NAME=CHARGER_RLCA_PICKUP
BODY_1_MASS=1
BODY_1_INERTIA=0.1, 0.1, 0.1
BODY_1_POS=0.45, -0.03, -0.02
BODY_1_MIRROR=1

SLIDER_1=CHARGER_RLCA_SLIDER
SLIDER_1_BODY_A=CHASSIS
SLIDER_1_BODY_B=CHARGER_RLCA_PICKUP
SLIDER_1_POS0=0.55, -0.03, -0.02
SLIDER_1_POS1=0.45, -0.03, -0.02
SLIDER_1_PARITY=-1

DJ5=CHARGER_RLCA_ADJUSTER
DJ5_BODY_A=CHASSIS
DJ5_BODY_B=CHARGER_RLCA_PICKUP
DJ5_POS0=0.55, -0.03, -0.02
DJ5_POS1=0.45, -0.03, -0.02

TOE_OUT=-0.00022
STATIC_CAMBER=0.25 
DJ2_LENGTH_OFFSET=0.00001 ;FLCA Camber
DJ3_LENGTH_OFFSET=0.00101 ;RLCA Caster

[FRONT_COILOVER_0] ;Corner spring
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=5000
PRELOAD=0
BODY_A=CHASSIS
BODY_B=HUB_L
POS0=0.10, 1.0, 0.0
POS1=0.10, 0.0, 0.0
BUMPSTOP_GAP=0.12
INSTALL_RATE=500000
RATE=35000

[FRONT_DAMPER_0]
BODY_A=CHASSIS
BODY_B=HUB_L
DAMP_BUMP=3000
DAMP_FAST_BUMP=1950
DAMP_FAST_BUMPTHRESHOLD=0.07								
DAMP_REBOUND=4900
DAMP_FAST_REBOUND=3400
DAMP_FAST_REBOUNDTHRESHOLD=0.075
POS0=0.3, 0.33, 0.0 
POS1=0.10, 0.0 5, 0.0
MIN_LENGTH=0.28	; use damper lengths for hard min/max travel.
MAX_LENGTH=0.45 





[REAR]
TYPE=COSMIC
BASEY=-0.295	 ; Distance of CG from the center of the wheel in meters. Rear Wheel Radius+BASEY=Rear CoG Actual CG height =(FWR+FBasey)+(RWR+Rbasey))/CG_LOCATION%
TRACK=1.48
ROD_LENGTH=0.12
HUB_MASS=30 
TOE_OUT=-0.00000
STATIC_CAMBER=0

BODY_0_NAME=AXLE			; adding extra rigid objects to the simulation
BODY_0_MASS=140			
BODY_0_INERTIA=1.6, 0.2, 0.2
BODY_0_POS=0.74, 0.0, 0.0

ENGINE_TORQUE_BODY=AXLE

J0=TOP_KINGPIN			; J0= has to exist, its contents is descriptive
J0_BODY_A=AXLE			; J0_BODY0 and BODY1 are the 2 objects this attaches to
J0_POS=0.198, 0.076, -0.01 	; default is body0 = -1, body1 = "this" (0 on left, 1 on right)
J0_KP=1				; _KP=1 is the joint at the top of the kingpin, =0 is bottom.  Use on a joint where BODY1=hub; tells the code which joints are WB_CAR_TOP and WB_CAR_BOTTOM effectively

J1=BOTTOM_KINGPIN
J1_BODY_A=AXLE
J1_POS=0.1807, -0.076, 0.01
J1_KP=0

STEER_JOINT_0=STEER_LINK
STEER_JOINT_0_BODY_A=AXLE
STEER_JOINT_0_POS0=0.65, -0.033, 0.166
STEER_JOINT_0_POS1=0.1304, -0.033, 0.166

DJ0=LEAF?
DJ0_BODY_B=AXLE
DJ0_POS0=0.20,-0.06,0.59 ; note unlike AXLE, it's always wheel-based coordinates so X changes
DJ0_POS1=0.18,-0.08,0.0

DJ1=LEAF_SIDEWAYS_STOPPER
DJ1_BODY_B=AXLE
DJ1_POS0=0.28,0.08,0.59 ; y.09
DJ1_POS1=0.18,0.06,0.0  ; y.15

[REAR_COILOVER_0]
RATE=23000
BUMPSTOP_LUT=(0=0|0.03=20000|0.06=100000)  	
BUMPSTOP_GAP=0.10		
BODY_B=AXLE
PRELOAD=0
PRELOAD_FORCE=3500
POS0=0.185, 0.45, 0.0
POS1=0.185, -0.07, 0.0
DAMP_BUMP=300
DAMP_FAST_BUMP=40
DAMP_REBOUND=300
DAMP_FAST_REBOUND=35

[REAR_DAMPER_0]
DAMP_BUMP=3000
DAMP_FAST_BUMP=1950
DAMP_FAST_BUMPTHRESHOLD=0.07								
DAMP_REBOUND=4900
DAMP_FAST_REBOUND=3400
DAMP_FAST_REBOUNDTHRESHOLD=0.075
POS0=0.3, 0.33, 0.0 
POS1=0.10, 0.0 5, 0.0
MIN_LENGTH=0.28	; use damper lengths for hard min/max travel.
MAX_LENGTH=0.44 


[GRAPHICS_OFFSETS]
WHEEL_LF=0.06					;Left front graphical offset of the wheel positioning in the x axis (width). + is left - is right movement
SUSP_LF=-0.06					;Left front graphical offset of the suspension positioning in the x axis (width). + is left - is right movement
WHEEL_RF=-0.06					; Right front as above
SUSP_RF=0.06				; Right front as above
WHEEL_LR=0.06					; Left rear as above
SUSP_LR=-0.06					; Left rear as above
WHEEL_RR=-0.03					; Right rear as above
SUSP_RR=-0.03			; Right rear as above

[DAMAGE]
MIN_VELOCITY=40				; MINUMUM VELOCITY TO START TAKING DAMAGE
GAIN=0.0004					; AMOUNT OF STEER ROD DEFLECTION FOR IMPACT KMH
MAX_DAMAGE=0.05			; MAXIMUM AMOUNT OF STEER ROD DEFLECTION ALLOWED
DEBUG_LOG=1					; ACTIVATES DAMAGE DEBUG IN THE LOG

