[HEADER]
VERSION=2

[BASIC]
WHEELBASE=2.595				; Wheelbase distance in meters
CG_LOCATION=0.53						; Front Weight distribution in percentance

[ARB]
FRONT=18000							; Front antiroll bar stifness. in Nm
REAR=5000								; Rear antiroll bar stifness. in Nm


[FRONT]
TYPE=DWB
BASEY=-0.18								; Distance of CG from the center of the wheel in meters. Front Wheel Radius+BASEY=front CoG. Actual CG height =(FWR+FBasey)+(RWR+Rbasey))/CG_LOCATION%
TRACK=1.490									; Track width in meters (from pivot 3D placement of the 3d model of a wheel)
ROD_LENGTH=0.135						; push rod length in meters. positive raises ride height, negative lowers ride height.
HUB_MASS=40
RIM_OFFSET=0.050							; masse sospese anteriori
WBCAR_TOP_FRONT=0.33, 0.11, 0.07
WBCAR_TOP_REAR=0.33, 0.105, -0.11
WBCAR_BOTTOM_FRONT=0.38, -0.105, -0.0
WBCAR_BOTTOM_REAR=0.38, -0.10, -0.35
WBTYRE_TOP=0.125, 0.11, -0.0185
WBTYRE_BOTTOM=0.08, -0.115, 0.0115
WBCAR_STEER=0.395, -0.05, 0.10
WBTYRE_STEER=0.075, -0.06, 0.11
TOE_OUT=0.00010							; Toe-out expressed as the length of the steering arm in meters
STATIC_CAMBER=-0.30						; Static Camber in degrees. Actual camber relative to suspension geometry and movement, check values in game
SPRING_RATE=30109						;assumed MR courtesy of arch 0.662
PROGRESSIVE_SPRING_RATE=0				; progressive spring rate in N/m/
BUMP_STOP_RATE=70000						; bump stop spring rate
BUMPSTOP_UP=0.110						; meters to upper bumpstop from the 0 design of the suspension
BUMPSTOP_DN=0.085						; meters to bottom bumpstop from the 0 design of the suspension
PACKER_RANGE=0.205						; Total suspension movement range, before hitting packers
DAMP_BUMP=4500							; Damper wheel rate stifness in N sec/m in compression
DAMP_FAST_BUMP=1434
DAMP_FAST_BUMPTHRESHOLD=0.120
DAMP_REBOUND=5000						; Damper wheel rate stifness in N sec/m in rebound
DAMP_FAST_REBOUND=2089
DAMP_FAST_REBOUNDTHRESHOLD=0.120

[REAR]
TYPE=DWB
BASEY=-0.21
TRACK=1.480
ROD_LENGTH=0.17
RIM_OFFSET=0.05
HUB_MASS=50
WBCAR_TOP_FRONT=0.375, 0.105, 0.06
WBCAR_TOP_REAR=0.375, 0.105, -0.11
WBCAR_BOTTOM_FRONT=0.56, -0.038, -0.10
WBCAR_BOTTOM_REAR=0.56, -0.04, -0.13
WBTYRE_TOP=0.15, 0.12, -0.01
WBTYRE_BOTTOM=0.14, -0.07, -0.10
WBCAR_STEER=0.465, -0.05, 0.13
WBTYRE_STEER=0.15, -0.065, 0.08
TOE_OUT=-0.000325
STATIC_CAMBER=-1.3
SPRING_RATE=23556               ;assumed MR courtesy of arch 0.826
PROGRESSIVE_SPRING_RATE=0
BUMP_STOP_RATE=30000
BUMPSTOP_UP=0.10
BUMPSTOP_DN=0.07
PACKER_RANGE=0.20
DAMP_BUMP=2880
DAMP_FAST_BUMP=1405
DAMP_FAST_BUMPTHRESHOLD=0.103
DAMP_REBOUND=3399
DAMP_FAST_REBOUND=6319
DAMP_FAST_REBOUNDTHRESHOLD=0.051

[_EXTRA_LINK_...]
TYPE = DISTANCE     ; possible values: FIXED, BALL, SLIDER, DISTANCE
FROM = BODY         ; possible values: BODY, HUB_LF, HUB_RF, HUB_LR, HUB_RR
TO = HUB_LR         ; possible values: BODY, HUB_LF, HUB_RF, HUB_LR, HUB_RR
CFM = 0.0000001     ; constraint force mixing
ERP = 0.3           ; error correction parameter

; And connection points (body ID and coordinates relative to it):
FROM_POS = BODY, 0.50,-0.3,-1.0  ; first point for DISTANCE joint
TO_POS = HUB_LR, -0.1,-0.08,0.08  ; second point for DISTANCE joint

[_EXTRA_LINK_...]
TYPE = DISTANCE     ; possible values: FIXED, BALL, SLIDER, DISTANCE
FROM = BODY         ; possible values: BODY, HUB_LF, HUB_RF, HUB_LR, HUB_RR
TO = HUB_RR         ; possible values: BODY, HUB_LF, HUB_RF, HUB_LR, HUB_RR
CFM = 0.0000001     ; constraint force mixing
ERP = 0.3           ; error correction parameter


; And connection points (body ID and coordinates relative to it):
FROM_POS = BODY, -0.50,-0.3,-1.0  ; first point for DISTANCE joint
TO_POS = HUB_RR, 0.10,-0.08,0.08  ; second point for DISTANCE joint

[GRAPHICS_OFFSETS]
//dont touch these Joog
WHEEL_LF=-0.01					;Left front graphical offset of the wheel positioning in the x axis (width). + is left - is right movement
SUSP_LF=-0.0					;Left front graphical offset of the suspension positioning in the x axis (width). + is left - is right movement
WHEEL_RF=0.01					; Right front as above
SUSP_RF=0.0				; Right front as above
WHEEL_LR=-0.01				; Left rear as above
SUSP_LR=-0.0					; Left rear as above
WHEEL_RR=0.01				; Right rear as above
SUSP_RR=0.0			; Right rear as above

[DAMAGE]
MIN_VELOCITY=40				; MINUMUM VELOCITY TO START TAKING DAMAGE
GAIN=0.0004					; AMOUNT OF STEER ROD DEFLECTION FOR IMPACT KMH
MAX_DAMAGE=0.05			; MAXIMUM AMOUNT OF STEER ROD DEFLECTION ALLOWED
DEBUG_LOG=1					; ACTIVATES DAMAGE DEBUG IN THE LOG

