[HEADER]
VERSION=3 ; emi v1.5

;CdA	1.08 CdA
;CdA	0.91 w/DRS
; downforce	при 144км/ч
;	106.72 kg	| 112.28 kg	Total	219.00 kg 
;	62.13 kg	| 56.87 kg	Total	119.00 kg    w/DRS

[WING_0]
NAME=FRONT
CHORD=0.50
SPAN=1.40
POSITION=0.000, 0.03, 1.95
LUT_AOA_CL=Aero_WING_Damage_Lift.lut
LUT_GH_CL=
CL_GAIN=1.429
LUT_AOA_CD=Aero_WING_Front_CD.lut
LUT_GH_CD=
CD_GAIN=1.429
ANGLE=0
ZONE_FRONT_CL=0.1    					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0.1    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

[WING_1]
NAME=CENTRE
CHORD=1.60
SPAN=1.55
POSITION=0.000, 0.260, -0.5
LUT_AOA_CL=Aero_WING_Centre_CD.lut
LUT_GH_CL=
CL_GAIN=0
LUT_AOA_CD=Aero_WING_Centre_CD.lut
LUT_GH_CD=
CD_GAIN=0.403
ANGLE=0
ZONE_FRONT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0.06     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0.06    					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

[WING_2]
NAME=REAR
CHORD=0.50
SPAN=1.50
POSITION=0.000, 0.10, -2.22
LUT_AOA_CL=Aero_WING_Damage_Lift.lut
LUT_GH_CL=
CL_GAIN=1.333
LUT_AOA_CD=Aero_WING_Rear_CD.lut
LUT_GH_CD=
CD_GAIN=1.333
ANGLE=0
ZONE_FRONT_CL=0    						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0.1     					; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0.1    				 	; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     						; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     						; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0    					 	; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     					; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.000

;|||||||||||||||||UNDER||||||||||||||||||

[WING_3]
NAME=DNIWE_F						; name of the wing
CHORD=0.5							; length of the wing in meters
SPAN=1.6							; width of the wing in meters. both help determine the frontal area
POSITION=0, -0.385, 1.94			; position in x,y,z starting from the CoG
LUT_AOA_CL=Aero_Under_CL.lut		; Coefficient of Lift lookup table
LUT_GH_CL=Aero_Height_CL.lut		; Height aero lift multiplier lookup table
CL_GAIN=1.250						; Coefficient of Lift multiplier 
LUT_AOA_CD=                 		; Coefficient of drag lookup table
LUT_GH_CD=                  		; Height aero drag multiplier table
CD_GAIN=0 							; 0.5
ANGLE=30
ZONE_FRONT_CL=0.2    ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-0.7

[WING_4]
NAME=GT WING							; name of the wing
CHORD=0.27								; length of the wing in meters
SPAN=1.61								; width of the wing in meters. both help determine the frontal area
POSITION=0, 0.68, -2.31				; position in x,y,z starting from the CoG
LUT_AOA_CL=Aero_WING_GT_CL.lut			; Coefficient of Lift lookup table
LUT_GH_CL=								; Height aero lift multiplier lookup table
CL_GAIN=2.300							; Coefficient of Lift multiplier 
LUT_AOA_CD=Aero_WING_GT_CD.lut			; Coefficient of drag lookup table
LUT_GH_CD=         		; Height aero drag multiplier table
CD_GAIN=2.300							; Coefficient of drag multiplier (for easy fine tuning)
ANGLE=30
ZONE_FRONT_CL=0    ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_FRONT_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_REAR_CL=0.2     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_REAR_CD=0    ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_LEFT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_LEFT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
ZONE_RIGHT_CL=0     ; CL=CL/(1.0+ZONE_0_CL*DAMAGE)
ZONE_RIGHT_CD=0     ; CD=CD*(1.0+ZONE_0_CD*DAMAGE)
YAW_CL_GAIN=-1

;|||||||||||||||||SIDE||||||||||||||||||||

[FIN_0]
NAME=Side F
CHORD=1.599260
SPAN=0.829105
POSITION=0, 0.024599, 1.49644
LUT_AOA_CL=Aero_FIN_Front_CL.lut
LUT_GH_CL=
CL_GAIN=0.754
LUT_AOA_CD=Aero_FIN_Front_CD.lut
LUT_GH_CD=
CD_GAIN=0.754
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[FIN_1]
NAME=Side C
CHORD=1.599260
SPAN=1.282390
POSITION=0, 0.2357, -0.102818
LUT_AOA_CL=Aero_FIN_Centre_CL.lut
LUT_GH_CL=
CL_GAIN=0.488
LUT_AOA_CD=Aero_FIN_Centre_CD.lut
LUT_GH_CD=
CD_GAIN=0.488
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[FIN_2]
NAME=Side R
CHORD=1.599260
SPAN=0.873975
POSITION=0, 0.120122, -1.70208
LUT_AOA_CL=Aero_FIN_Rear_CL.lut
LUT_GH_CL=
CL_GAIN=0.715
LUT_AOA_CD=Aero_FIN_Rear_CD.lut
LUT_GH_CD=
CD_GAIN=0.715
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[FIN_3]
NAME=Side GT
CHORD=0.544853
SPAN=0.175883
POSITION=0, 0.70548, -2.19204
LUT_AOA_CL=Aero_FIN_Rear_CL.lut
LUT_GH_CL=
CL_GAIN=2.123 ;10.435*(0.118/0.580)
LUT_AOA_CD=Aero_FIN_Rear_CD.lut
LUT_GH_CD=
CD_GAIN=2.123
ANGLE=0
ZONE_FRONT_CL=0
ZONE_FRONT_CD=0
ZONE_REAR_CL=0
ZONE_REAR_CD=0
ZONE_LEFT_CL=0
ZONE_LEFT_CD=0
ZONE_RIGHT_CL=0
ZONE_RIGHT_CD=0
YAW_CL_GAIN=0

[DYNAMIC_CONTROLLER_0]
WING=4
COMBINATOR=ADD
INPUT=LIGHT_EXTRA_A
LUT=(0=0|1=-30)
FILTER=0.992
UP_LIMIT=30
DOWN_LIMIT=0

[DYNAMIC_CONTROLLER_1]
WING=4
COMBINATOR=ADD
INPUT=BRAKE
LUT=(0=0|0.2=0|0.3=30)
FILTER=0.992
UP_LIMIT=30
DOWN_LIMIT=0

[DYNAMIC_CONTROLLER_2]
WING=3
COMBINATOR=ADD
INPUT=LIGHT_EXTRA_A
LUT=(0=0|1=-30)
FILTER=0.992
UP_LIMIT=30
DOWN_LIMIT=0

[DYNAMIC_CONTROLLER_3]
WING=3
COMBINATOR=ADD
INPUT=BRAKE
LUT=(0=0|0.2=0|0.3=30)
FILTER=0.992
UP_LIMIT=30
DOWN_LIMIT=0