[HEADER]
VERSION=2

[_EXTENSION]
ENABLE=1
USE_ADVANCED_SYSTEM=1

[DATA]
MAX_TORQUE=5000
FRONT_SHARE=0.5			; Percentance of brake torque at front axis
HANDBRAKE_TORQUE=1200
COCKPIT_ADJUSTABLE=0   ; 0: no bias control from cockpit, 1: bias control from cockpit
ADJUST_STEP=0.5   ; step for bias cockpit adjustment.

[DATA2]
MAX_PRESSURE_SUM=1800

[FRONT]
DISC_EFFECTIVE_RADIUS=0.1893
PISTON_DIAMETER_0=0.034
PISTON_DIAMETER_1=0.034
PISTON_DIAMETER_2=0.038
PISTON_DIAMETER_3=0.038
PISTON_DIAMETER_4=0.040
PISTON_DIAMETER_5=0.040

[REAR]
DISC_EFFECTIVE_RADIUS=0.1675
PISTON_DIAMETER_0=0.030
PISTON_DIAMETER_1=0.030
PISTON_DIAMETER_2=0.032
PISTON_DIAMETER_3=0.032

[TEMPS_FRONT]
COOL_TRANSFER=0.0020
TORQUE_K=0.24
COOL_SPEED_FACTOR_0=0.125
COOL_SPEED_FACTOR=0.110
CORE_TRANSFER_IN=0.0441
CORE_TRANSFER_OUT=0.305
CORE_TRANSFER_AIR=0.00011
DEFAULT_BLANKING=0
PERF_CURVE=brakes_Type_CC_pad_M.lut
; PERF_CURVE=(|0=0.47|100=0.47|)

[TEMPS_REAR]
COOL_TRANSFER=0.0020
TORQUE_K=0.24
COOL_SPEED_FACTOR_0=0.113
COOL_SPEED_FACTOR=0.065
CORE_TRANSFER_IN=0.047
CORE_TRANSFER_OUT=0.288
CORE_TRANSFER_AIR=0.00011
DEFAULT_BLANKING=0
PERF_CURVE=brakes_Type_CC_pad_M.lut
; PERF_CURVE=(|0=0.47|100=0.47|)

; Front	420	6.5	7	Type_CC	M_Caliper	34	2	38	2	40	2
; Rear	370	5.2	1900	Type_CC	M_Caliper	30	2	32	2		