[CONTROLLER_0]
INPUT=STEER_DEG  ; OVERSTEER_FACTOR REAR_SPEED_RATIO SLIPANGLE_FRONT_AVERAGE SLIPANGLE_FRONT_MAX SLIPANGLE_REAR_AVERAGE SLIPANGLE_REAR_MAX RPMS STEER_DEG WHEEL_STEER_DEG LATG
COMBINATOR=ADD
LUT=(-200=0|0=0|200=0)
FILTER=0.995
UP_LIMIT=2
DOWN_LIMIT=-2
;Fiction for the work of damage to the rear arms.