[HEADER]
VERSION=4

[_EXTENSION]
TORQUE_MODE_EX=2
FIX_PROGRESSIVE_RATE=1
DAMPER_LUTS=1

;[ODE]                          ;optional - tuning these parameters can help with stability. See Open Dynamics Engine Manual (http://ode.org/wiki/index.php/Manual#Joint_error_and_the_Error_Reduction_Parameter_.28ERP.29) for more information.
;ERP=0.9                        ;this is the AC default for certain joint types, others (and global value) are 0.3
;CFM=1                          ;*10^-7 - just did this to keep numbers more reasonable

[BASIC]
WHEELBASE=2.720
CG_LOCATION=0.514

[ARB]
FRONT=90000
REAR=26000

[FRONT]
TYPE=COSMIC
BASEY=-0.17
TRACK=1.725
HUB_MASS=45
RIM_OFFSET=-0.010

;S650 GTD Передние тела
BODY_0_NAME=F_S650GTD_Upper_shim
BODY_0_MASS=0.3
BODY_0_INERTIA=0.005, 0.03, 0.23
BODY_0_POS=0.322872, 0.117794, -0.050312
BODY_0_MIRROR=1

BODY_1_NAME=F_S650GTD_LCA_R
BODY_1_MASS=6
BODY_1_INERTIA=0.432, 0.054, 0.03
BODY_1_POS=0.283307, -0.169572, -0.034536
BODY_1_MIRROR=1

BODY_2_NAME=F_S650GTD_Caliper
BODY_2_MASS=6
BODY_2_INERTIA=0.157, 0.382, 0.152
BODY_2_POS=-0.044177, -0.096473, -0.114484
BODY_2_MIRROR=1

;S650 GTD Верхнее соединение
SLIDER_0=F_S650GTD_thickness_Upper_shim
SLIDER_0_BODY_B=F_S650GTD_Upper_shim
SLIDER_0_POS_A=0.35, 0.117794, -0.050312
SLIDER_0_POS_B=0.322872, 0.117794, -0.050312

DJ0=F_S650GTD_thickness_Upper_shim_adj
DJ0_BODY_B=F_S650GTD_Upper_shim
DJ0_POS_A=0.35, 0.117794, -0.050312
DJ0_POS_B=0.322872, 0.117794, -0.050312

DJ1=F_S650GTD_UCA_F
DJ1_BODY_A=F_S650GTD_Upper_shim
DJ1_POS_A=0.322872, 0.127044, 0.060313
DJ1_POS_B=0.080694, 0.121976, -0.033181
DJ1_KP=1

DJ2=F_S650GTD_UCA_R
DJ2_BODY_A=F_S650GTD_Upper_shim
DJ2_POS_A=0.322872, 0.108544, -0.108544
DJ2_POS_B=0.080694, 0.121976, -0.033181

;S650 GTD Нижнее соединение
DJ3=F_S650GTD_LCA_F
DJ3_POS_A=0.424599, -0.080727, 0.287236
DJ3_POS_B=0.080694, -0.085795, 0.020018

J0=F_S650GTD_LCA_R1
J0_BODY_B=F_S650GTD_LCA_R
J0_POS=0.483228, -0.167621, -0.048542

DJ4=F_S650GTD_LCA_R1_X_axle_Locker
DJ4_BODY_B=F_S650GTD_LCA_R
DJ4_POS_A=0.483228, -0.167621, -0.198542
DJ4_POS_B=0.483228, -0.017621, -0.048542

J1=F_S650GTD_LCA_R2
J1_BODY_A=F_S650GTD_LCA_R
J1_POS=0.080694, -0.185474, -0.018544

STEER_JOINT_0=F_S650GTD_TOE
STEER_JOINT_0_POS_A=0.490, -0.154, 0.145
STEER_JOINT_0_POS_B=0.055, -0.168, 0.123

J2=F_S650GTD_KPI_0
J2_BODY_A=F_S650GTD_Caliper
J2_POS=0.035408, -0.135634, 0.000737
J2_KP=0

HJ0=F_S650GTD_Caliper_Locker
HJ0_BODY_A=F_S650GTD_Caliper
HJ0_POS_A=0.150, -0.05, 0.000737
HJ0_POS_B=0.150, -0.135634, 0.000737

TOE_OUT=0.00000		
STATIC_CAMBER=-1.3	;-1.3 street| -2.3 Track
STEER_JOINT_0_LENGTH_OFFSET=0.0002	;-0.05
DJ0_LENGTH_OFFSET=-0.0046 ;Upper Shim Camber

[FRONT_COILOVER_0] ;CORNER SPRING + DAMPER
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=0
PRELOAD=0.0030;-0.0050; 0.0235

BODY_B=F_S650GTD_LCA_R
POS_A=0.300027, 0.438738, -0.059389
POS_B=0.194968, -0.180406, -0.027879

MIN_LENGTH=0.585 ;N=629
MAX_LENGTH=0.670
BUMPSTOP_GAP=0.026;	51mm

; END_VTAPER=0.05			;velocity at which rate tapers off in rebound
; END_VMAX=0.20			;velocity where end limit adds 0 force in rebound (these parameters help with energy loss to avoid bouncing after crash landings)

INSTALL_RATE=2200000
RATE=200000
;SPRING_LUT=suspensions_Front_spring.lut

; [FRONT_SPRING_0]
; POS_A=0, 1, 0
; POS_B=0, 0, 0
; RATE=5000

[REAR]
TYPE=COSMIC
BASEY=-0.17
TRACK=1.734
HUB_MASS=50
RIM_OFFSET=-0.010

;S650 GTD Задние тела
BODY_0_NAME=R_S650GTD_Rocker
BODY_0_MASS=2
BODY_0_INERTIA=0.133, 0.158, 0.138
BODY_0_POS=0.439447, 0.380832, -0.05707
BODY_0_MIRROR=1

BODY_1_NAME=R_S650GTD_LCA
BODY_1_MASS=8
BODY_1_INERTIA=0.472, 0.048, 0.258
BODY_1_POS=0.305463, -0.072989, -0.000051
BODY_1_MIRROR=1

;S650 GTD Верхняя часть
HJ0=R_S650GTD_Rocker_Axle
HJ0_BODY_B=R_S650GTD_Rocker
HJ0_POS_A=0.477132, 0.328522, 0.061962
HJ0_POS_B=0.477132, 0.328522, -0.176102

DJ0=R_S650GTD_Push_Rod
DJ0_BODY_A=R_S650GTD_Rocker
DJ0_BODY_B=R_S650GTD_LCA
DJ0_POS_A=0.384664, 0.365649, -0.057891
DJ0_POS_B=0.162942, -0.052089, -0.046893

DJ1=R_S650GTD_UCA
DJ1_POS_A=0.424697, 0.085738, 0.029475
DJ1_POS_B=0.162828, 0.104873, 0.002583

;S650 GTD Нижняя часть
J0=R_S650GTD_LCA_F1
J0_BODY_B=R_S650GTD_LCA
J0_POS=0.40231, -0.076376, 0.121962

DJ2=R_S650GTD_LCA_F2
DJ2_BODY_A=R_S650GTD_LCA
DJ2_POS_A=0.080415, -0.076376, 0.067157
DJ2_POS_B=0.080415, -0.114662, 0.067157

; DJ3=R_S650GTD_LCA_F2_X_axle_Locker
; DJ3_BODY_A=R_S650GTD_LCA
; DJ3_POS_A=0.080415, -0.076376, 0.017157
; DJ3_POS_B=0.080415, -0.114662, 0.067157

J1=R_S650GTD_LCA_R1
J1_BODY_B=R_S650GTD_LCA
J1_POS=0.502985, -0.076376, -0.099038

J2=R_S650GTD_LCA_R2
J2_BODY_A=R_S650GTD_LCA
J2_POS=0.123004, -0.076376, -0.127038

STEER_JOINT_0=R_S650GTD_TOE
STEER_JOINT_0_POS_A=0.445, -0.142, 0.057
STEER_JOINT_0_POS_B=0.105, -0.150, 0.023

TOE_OUT=0			;+0.12
STATIC_CAMBER=-1.1	;-1.1 street & Track
;DJ2_LENGTH_OFFSET=-0.00051 ;RLCA Camber

[REAR_COILOVER_0] ;Push-Rod Spring & Damper Left
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=0
PRELOAD=-0.0050;-0.0135; 0.0196
PARITY=0

BODY_B=R_S650GTD_Rocker
POS_A=1.1965, 0.257715, 0.011962
POS_B=0.48131, 0.427288, 0.011962

MIN_LENGTH=0.680	; N=735mm
MAX_LENGTH=0.785	;91.8mm + 167mm
BUMPSTOP_GAP=0.033;	61-28mm

; END_VTAPER=0.05			;velocity at which rate tapers off in rebound
; END_VMAX=0.20			;velocity where end limit adds 0 force in rebound (these parameters help with energy loss to avoid bouncing after crash landings)

INSTALL_RATE=2200000
RATE=170000
;SPRING_LUT=suspensions_Rear_spring.lut

[REAR_COILOVER_1] ;Push-Rod Spring & Damper Right
ELECT_LOG=CORNER
PULL_FORCE=0
PRELOAD_FORCE=0
PRELOAD=-0.0050;-0.0135; 0.0196
PARITY=1

BODY_B=R_S650GTD_Rocker
POS_A=1.1965, 0.257715, -0.126102
POS_B=0.48131, 0.427288, -0.126102

MIN_LENGTH=0.680	; N=735mm
MAX_LENGTH=0.785	;91.8mm + 167mm
BUMPSTOP_GAP=0.033;	61-28mm

; END_VTAPER=0.05			;velocity at which rate tapers off in rebound
; END_VMAX=0.20			;velocity where end limit adds 0 force in rebound (these parameters help with energy loss to avoid bouncing after crash landings)

INSTALL_RATE=2200000
RATE=170000
;SPRING_LUT=suspensions_Rear_spring.lut

[GRAPHICS_OFFSETS]
WHEEL_LF=-0.000
SUSP_LF=-0.000
WHEEL_RF=0.000
SUSP_RF=0.000
WHEEL_LR=-0.000
SUSP_LR=-0.000
WHEEL_RR=0.000
SUSP_RR=0.000

[DAMAGE]
MIN_VELOCITY=40
GAIN=0.0004
MAX_DAMAGE=0.02
DEBUG_LOG=1