[HEADER]
VERSION=10 ; emi 2.28
; Built by Ini-F calculator, hope you like it :)

[_EXTENSION]
USE_NEW_RR_SLIP=1

MAX_RAY_ANGLE=60
LATERAL_RAYS=1
LONGITUDINAL_RAYS=1





[THERMAL_MODEL]
VERSION=2

[VIRTUALKM]
USE_LOAD=1

[EXPLOSION]
TEMPERATURE=300

[ADDITIONAL1]
BLANKETS_TEMP=40

[COMPOUND_DEFAULT]
INDEX=1

[FRONT]
NAME=Michelin Pilot Sport 4S
SHORT_NAME=PS4S
TYPE_HINT=TREADED
WIDTH=0.31   ;0.325-0.015  /30
RADIUS=0.3517
RIM_RADIUS=0.2733      ;20R+1.5
ANGULAR_INERTIA=2.2348    ;R10.9kg  T14.11kg  D6.5kg, 420mm
DAMP=800
RATE=398050
CAMBER_SPRING_MULT=tire_camber_spring_k.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_45.lut
SPEED_SENSITIVITY=0.00082
RELAXATION_LENGTH=0.038
ROLLING_RESISTANCE_0=10
ROLLING_RESISTANCE_1=0.002724
ROLLING_RESISTANCE_SLIP=841

CAMBER_GAIN=0.123
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_4_A.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=7.77




CX_MULT=1.10
BRAKE_DX_MOD=0.05

PRESSURE_STATIC=30
PRESSURE_SPRING_GAIN=12935
PRESSURE_FLEX_GAIN=0.45
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=35.5
; F523.03kg | R509.19kg   2064.44kg / 50.67%
FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_PS4S_Front_325_DX.lut
DY_CURVE=tire_PS4S_Front_325_DY.lut
FLEX_GAIN=0.0325

FALLOFF_LEVEL_CURVE=tire_heat_road_70_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_70_speed.lut
FALLOFF_LEVEL=0.5
FALLOFF_SPEED=50
DROPOFF_FACTOR_0=7.07
DROPOFF_FACTOR_1=0.78









RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_FRONT]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_70_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_FRONT]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000348
SURFACE_TO_AMBIENT=0.0358
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015

FRICTION_TEMP_K=1

[REAR]
NAME=Michelin Pilot Sport 4S
SHORT_NAME=PS4S
TYPE_HINT=TREADED
WIDTH=0.33   ;0.345-0.015  /30
RADIUS=0.3577
RIM_RADIUS=0.2733      ;20R+1.5
ANGULAR_INERTIA=2.3328    ;R11.5kg  T15kg  D5.2kg, 370mm
DAMP=800
RATE=393970
CAMBER_SPRING_MULT=tire_camber_spring_k.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_45.lut
SPEED_SENSITIVITY=0.00074
RELAXATION_LENGTH=0.032
ROLLING_RESISTANCE_0=10
ROLLING_RESISTANCE_1=0.002979
ROLLING_RESISTANCE_SLIP=851

CAMBER_GAIN=0.127
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_4_A.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=8.14




CX_MULT=1.10
BRAKE_DX_MOD=0.05

PRESSURE_STATIC=30
PRESSURE_SPRING_GAIN=12799
PRESSURE_FLEX_GAIN=0.45
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=35

FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_PS4S_Rear_345_DX.lut
DY_CURVE=tire_PS4S_Rear_345_DY.lut
FLEX_GAIN=0.0335

FALLOFF_LEVEL_CURVE=tire_heat_road_70_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_70_speed.lut
FALLOFF_LEVEL=0.5
FALLOFF_SPEED=50
DROPOFF_FACTOR_0=7.07
DROPOFF_FACTOR_1=0.78









RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_REAR]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_70_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_REAR]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000306
SURFACE_TO_AMBIENT=0.038
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
FRICTION_TEMP_K=1

[FRONT_1]
NAME=Michelin Pilot Sport Cup 2 R
SHORT_NAME=PSC2R
TYPE_HINT=RACING_TREADED
WIDTH=0.31   ;0.325-0.015  /30
RADIUS=0.3517
RIM_RADIUS=0.2733      ;20R+1.5
ANGULAR_INERTIA=2.2348    ;R10.9kg  T14.11kg  D6.5kg, 420mm
DAMP=800
RATE=398050
CAMBER_SPRING_MULT=tire_camber_spring_k.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_30.lut
SPEED_SENSITIVITY=0.00082
RELAXATION_LENGTH=0.038
ROLLING_RESISTANCE_0=17
ROLLING_RESISTANCE_1=0.002724
ROLLING_RESISTANCE_SLIP=841

CAMBER_GAIN=0.123
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_4_A.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=7.77




CX_MULT=1.10
BRAKE_DX_MOD=0.05

PRESSURE_STATIC=30
PRESSURE_SPRING_GAIN=12935
PRESSURE_FLEX_GAIN=0.45
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=35.5
; F523.03kg | R509.19kg   2064.44kg / 50.67%
FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_PSC2R_Front_325_DX.lut
DY_CURVE=tire_PSC2R_Front_325_DY.lut
FLEX_GAIN=0.0325

FALLOFF_LEVEL_CURVE=tire_heat_road_85_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_85_speed.lut
FALLOFF_LEVEL=0.5
FALLOFF_SPEED=50
DROPOFF_FACTOR_0=8.88
DROPOFF_FACTOR_1=0.9
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_FRONT_1]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_85_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_FRONT_1]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000348
SURFACE_TO_AMBIENT=0.0358
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
FRICTION_TEMP_K=1

[REAR_1]
NAME=Michelin Pilot Sport Cup 2 R
SHORT_NAME=PSC2R
TYPE_HINT=RACING_TREADED
WIDTH=0.33   ;0.345-0.015  /30
RADIUS=0.3577
RIM_RADIUS=0.2733      ;20R+1.5
ANGULAR_INERTIA=2.3328    ;R11.5kg  T15kg  D5.2kg, 370mm
DAMP=800
RATE=393970
CAMBER_SPRING_MULT=tire_camber_spring_k.lut

DY0=1.3027   ; не используется
DY1=-0.048
DX0=1.3115
DX1=-0.046
FLEX=0.000684
XMU=0.27     ; не используется

WEAR_CURVE=tire_wear_dy_road_30.lut
SPEED_SENSITIVITY=0.00074
RELAXATION_LENGTH=0.032
ROLLING_RESISTANCE_0=17
ROLLING_RESISTANCE_1=0.002979
ROLLING_RESISTANCE_SLIP=851

CAMBER_GAIN=0.127
DCAMBER_0=1.1
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy_4_A.lut
DCAMBER_LUT_SMOOTH=1
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=8.14




CX_MULT=1.10
BRAKE_DX_MOD=0.05

PRESSURE_STATIC=30
PRESSURE_SPRING_GAIN=12799
PRESSURE_FLEX_GAIN=0.45
PRESSURE_RR_GAIN=0.40
PRESSURE_D_GAIN=0.003
PRESSURE_IDEAL=35

FZ0=3000
LS_EXPX=0.5     ; не используется
LS_EXPY=0.5
DX_REF=0.5
DY_REF=0.5      ; не используется
DX_CURVE=tire_PSC2R_Rear_345_DX.lut
DY_CURVE=tire_PSC2R_Rear_345_DY.lut
FLEX_GAIN=0.0335

FALLOFF_LEVEL_CURVE=tire_heat_road_85_level.lut
FALLOFF_SPEED_CURVE=tire_heat_road_85_speed.lut
FALLOFF_LEVEL=0.5
FALLOFF_SPEED=50
DROPOFF_FACTOR_0=8.88
DROPOFF_FACTOR_1=0.9
RADIUS_ANGULAR_K=0.01
RADIUS_ANGULAR_K_2=0.05
ROLLING_RADIUS_MULT=0.1

[THERMAL_REAR_1]
SURFACE_TRANSFER=0.98
PATCH_TRANSFER=0.002
CORE_TRANSFER=0
INTERNAL_CORE_TRANSFER=0
FRICTION_K=0.0084
ROLLING_K=0
PERFORMANCE_CURVE=tire_heat_road_85_mu.lut
GRAIN_GAMMA=1
GRAIN_GAIN=0
BLISTER_GAMMA=1
BLISTER_GAIN=0
COOL_FACTOR=5
SURFACE_ROLLING_K=0.04

[THERMAL2_REAR_1]
CARCASS_ROLLING_K=0.25
BRAKE_TO_CORE=0.000306
SURFACE_TO_AMBIENT=0.038
SURFACE_TO_CARCASS=0.033
CARCASS_TO_SURFACE=0.125
CARCASS_TO_CORE=0.0050
CORE_TO_CARCASS=0.0010
CORE_TO_AMBIENT=0.0015
FRICTION_TEMP_K=1