[HEADER]
VERSION=extended-2									; version number

[INFO]
SCREEN_NAME=Dima Brutskiy pro/prospec

[BASIC]
GRAPHICS_OFFSET=0.0000, -0.54135, -0.114  ;( wheelbase * cg diff)
GRAPHICS_PITCH_ROTATION=0

;GRAPHICS_OFFSET=0.00,-.571365,-0.056;-0.073; 3 axis correction (x,y,z), applies only to the 3D object of the car. in meters
;GRAPHICS_PITCH_ROTATION=0				; changes 3D object rotation in pitch
TOTALMASS=1336 ; 3036lb+driver ; total vehicle weight in kg with driver and no fuel
INERTIA=1.65,1.35,4.5
;INERTIA=1.250, 1.350, 4.300
;INERTIA=1.64,1.22,4.35 					; car polar inertia. Calculated from the car dimensions. Just enter the generic width,height, 
 
[GRAPHICS]
DRIVEREYES=0.361050,1.099270,-0.179508
ONBOARD_EXPOSURE=20
OUTBOARD_EXPOSURE=35
ON_BOARD_PITCH_ANGLE=-14.998494
BUMPER_CAMERA_POS=0.000000,0.220000,2.400000
BONNET_CAMERA_POS=0.000000,0.700000,0.740000
MIRROR_POSITION=0.0,1.3,0.5 					; Position used to render the mirror
USE_ANIMATED_SUSPENSIONS=0
SHAKE_MUL=3										; Camera onboard G forces multiplier
FUEL_LIGHT_MIN_LITERS=4
BONNET_CAMERA_PITCH=0.000000
BUMPER_CAMERA_PITCH=0.000000

[CONTROLS]
FFMULT=1.2
STEER_ASSIST=1.0
;STEER_LOCK= 450; 


;STEER_RATIO=8.32    
; for 450


;; (576 + spacers)

STEER_LOCK= 540; 	real steer lock, doesnt work on any current dd wheelbases

STEER_RATIO=9.94	
;  for 540

LINEAR_STEER_ROD_RATIO=0.0014


ENABLE_REAL_FEEL=1
ASSIST_TORQUE_MAX=35;
;Max/reference torque of power steering system in Nm
ASSIST_MAP_0=car_ps_torque.lut
[FUEL]
CONSUMPTION=0.0048				; fuel consumption. In one second the consumption is (rpm*gas*CONSUMPTION)/1000 litres
FUEL=23							; default starting fuel in litres
MAX_FUEL=40	; just extra for weight transfer testing. 22.7 is max					; max fuel in litres

[FUELTANK]
POSITION=-0.34,-0.15,-.9

[RIDE]
PICKUP_FRONT_HEIGHT=-0.34		; Height of the front ride height pickup point in meters WRT cg
PICKUP_REAR_HEIGHT=-0.25 ; -0.27

[PIT_STOP]
TYRE_CHANGE_TIME_SEC=10				; time spent to change each tyre
FUEL_LITER_TIME_SEC=0.1				; time spent to put 1 lt of fuel inside the car
BODY_REPAIR_TIME_SEC=2				; time spent to repair 10% of body damage
ENGINE_REPAIR_TIME_SEC=2			; time spent to repair 10% of engine damage
SUSP_REPAIR_TIME_SEC=2				; time spent to repair 10% of suspension damage
