[HEADER]
VERSION=3
FLASHING_BLINK_TIME=0.15
FLASHING_REPEAT=8



[BRAKE_0]
NAME=EXT_TAILLIGHTS_BRAKE
COLOR=4,1,0
OFF_COLOR=0,0,0



[BRAKE_1]
NAME=EXT_LED_STRIP_BRAKE_F_pad_SUB0
COLOR=8,0,0

[BRAKE_2]
NAME=EXT_LED_STRIP_BRAKE_F_SUB1
COLOR=250,113,3

[BRAKE_3]
NAME=EXT_LED_STRIP_BRAKE_R_SUB1
COLOR=250,3,3

[BRAKE_4]
NAME=EXT_LED_STRIP_BRAKE_R_pad_SUB0
COLOR=5,0,0

[BRAKE_5]
NAME=EXT_TAILLIGHTS_frame
COLOR=1,0,0
OFF_COLOR=0,0,0

[BRAKE_6]
NAME=EXT_TAILLIGHTS_frame_SUB1
COLOR=1130,5,0
OFF_COLOR=0,0,0


[LIGHT_0]
NAME=GEO_Chassis_taillight_brake_reflector
COLOR=5,0,0

[LIGHT_1]
NAME=headlight-leds
COLOR=6,6,6

[LIGHT_2]
NAME=FRONT_LIGHT_GLASSTUBE
COLOR=1,1,1.2


[LIGHT_3]
NAME=g_headlight_far_002
COLOR=5.2,5,7.7



[LIGHT_4]
NAME=lcdScreen
INTENSITY=30
COLOR=0,0,0
OFF_COLOR=4,4,4

###########  EXTRA


[LIGHT_5]
NAME=EXT_HEADLIGHTS_LB_BULB
COLOR=12,11,7

[LIGHT_6]
NAME=EXT_HEADLIGHTS_LB_CHROME
COLOR=12,11,7


[LIGHT_7]
NAME=brake_lr_004
COLOR=0.22,0.2,0.15


[LIGHT_8]
NAME=brake_lf_004
COLOR=0.22,0.2,0.15


[LIGHT_9]
NAME=brake_rr
COLOR=0.22,0.2,0.15


[LIGHT_10]
NAME=brake_rf
COLOR=0.22,0.2,0.15

[LIGHT_11]
NAME=Box006_002
COLOR=0.22,0.2,0.15

[LIGHT_12]
NAME=SUSP_LF01_SUB12
COLOR=0.22,0.2,0.15

[LIGHT_13]
NAME=SUSP_RF01_SUB28
COLOR=0.22,0.2,0.15

[LIGHT_14]
NAME=fenders_c10_002_002
COLOR=0.22,0.2,0.15

[LIGHT_15]
NAME=fenders_c08_002_002
COLOR=0.05,0.02,0.09

[LIGHT_16]
NAME=GEO_FRONT_fendersbody_c11_002_004_002
COLOR=0.05,0.02,0.09

[LIGHT_17]
NAME=GEO_DISPLAY
INTENSITY=30
COLOR=-.4,-.4,-.4
OFF_COLOR=0,0,0


[LIGHT_18]
NAME=BUTTONBOX
COLOR=0.1,0.1,0.1


[LIGHT_19]
NAME=ruggerradio-display
COLOR=0.5,0.5,0.8
OFF_COLOR=0,0.0,0.0


[LIGHT_20]
NAME=headlightframe
COLOR=2,2,2




[REVERSE_0]
NAME=EXT_TAILLIGHTS_REVERSE
COLOR=200,200,200


