[HEADER] ; gt  2026 0.6
;updated 05.21/2026
;changed front width
;changed all dcamber0/1
;changed all camber gain from 0.1 to 0.125
;changed friction limit angle from ~7 to 12
;changed heat generation
;
;update 6/14 
;dx/dy ref increased after aero tuning
; cx_mult=0.85


VERSION=10

[_EXTENSION]
PRACTICAL_TEMP_RATIO=0.9
USE_NEW_RR_SLIP=1
LATERAL_RAYS=3
LONGITUDINAL_RAYS=3
SMOOTH_LOAD_SENS=0
ENABLE_RAY_FORCE_WEIGHTING=0

[THERMAL_MODEL]
VERSION=2

[VIRTUALKM]
USE_LOAD=1

[EXPLOSION]
TEMPERATURE=650

[ADDITIONAL1]
BLANKETS_TEMP=80

[COMPOUND_DEFAULT]
INDEX=0

[FRONT]
NAME=Champiro SX2
SHORT_NAME=GTF
WIDTH=0.248
RADIUS=0.3179
RIM_RADIUS=0.2286
ANGULAR_INERTIA=1.750
DAMP=450
RATE=245000
CAMBER_SPRING_MULT=tire_camber_spring_k.lut
WEAR_CURVE=tire_wear.lut
SPEED_SENSITIVITY=0.001
RELAXATION_LENGTH=0.07
ROLLING_RESISTANCE_0=14.5
ROLLING_RESISTANCE_1=0.00025
ROLLING_RESISTANCE_SLIP=800
CAMBER_GAIN=0.125
DCAMBER_0=1.55
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy.lut
DCAMBER_LUT_SMOOTH=0
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=9
CX_MULT=0.85
FLEX_GAIN=0.015
	;COMBINED_FACTOR=2
	;COMBINED_FACTOR_1=0.36
COMBINED_FACTOR_BRAKE_MULT=1.00
COMBINED_FACTOR_LOAD_K=0.0
BRAKE_DX_MOD=0.017
PRESSURE_STATIC=26.0
PRESSURE_SPRING_GAIN=8600
PRESSURE_FLEX_GAIN=-0.35
PRESSURE_RR_GAIN=0.60
PRESSURE_D_GAIN=0.0022
PRESSURE_IDEAL=28.0
FZ0=2800
DY_REF=1.47
DX_REF=1.425          ; Longitudinal grip
LS_EXPY=0.85         ; Lateral load sensitivity
LS_EXPX=0.89         ; Longitudinal load sensitivity
	;DY_CURVE=sx2_lat.lut ; removed
	;DX_CURVE=sx2_long.lut ; rempved
FALLOFF_LEVEL_CURVE=tire_heat_level.lut
FALLOFF_SPEED_CURVE=tire_heat_speed.lut
;FALLOFF_LEVEL=0.88
;FALLOFF_SPEED=7
	;DROPOFF_FACTOR_0=10.5
	;DROPOFF_FACTOR_1=1.00
	;FALLOFF_YSPEED_MULT=1.00

	;SAT_MULT=	1.1
	;SAT_SPEED=	1.2
	;SAT_PEAK_K=0.50
	;SAT_MULT_K=0.03
	;SAT_MIN_REF=0.03
	;SAT_LOAD_K=0.000010
SIDEWALL_K_MULT=	0.85 	; Multiplier for sidewall stiffness (affects flex & handling feel)
SIDEWALL_K_MULT_X=	1.2 	; Longitudinal sidewall stiffness multiplier
RADIUS_ANGULAR_K=	0.010 	; How much tire radius grows with wheel rotation speed (effective rolling radius)
RADIUS_ANGULAR_K_2=	0.02	; Secondary / higher speed effect on radius
ROLLING_RADIUS_MULT=	0.38	; Overall multiplier for rolling radius

; OLD deprecated
XMU=0.00
DY0=0.00
DY1=0.00
DX0=0.00
DX1=0.00
FLEX=0.00

[REAR]
NAME=Champiro SX2
SHORT_NAME=GTF
WIDTH=0.248
RADIUS=0.3179
RIM_RADIUS=0.2286
ANGULAR_INERTIA=1.750
DAMP=450
RATE=245000
CAMBER_SPRING_MULT=tire_camber_spring_k.lut
WEAR_CURVE=tire_wear.lut
SPEED_SENSITIVITY=0.001
RELAXATION_LENGTH=0.07
ROLLING_RESISTANCE_0=14.5
ROLLING_RESISTANCE_1=0.00025
ROLLING_RESISTANCE_SLIP=800
CAMBER_GAIN=0.125
DCAMBER_0=1.55
DCAMBER_1=-13
DCAMBER_LUT=tire_camber_dy.lut
DCAMBER_LUT_SMOOTH=0
DX_CAMBER_REF=3
DX_CAMBER_MULT=0.98
FRICTION_LIMIT_ANGLE=9
CX_MULT=.85
FLEX_GAIN=0.015
	;COMBINED_FACTOR=2
	;COMBINED_FACTOR_1=0.36
COMBINED_FACTOR_BRAKE_MULT=1.00
COMBINED_FACTOR_LOAD_K=0.0
BRAKE_DX_MOD=0.017
PRESSURE_STATIC=26.0
PRESSURE_SPRING_GAIN=8600
PRESSURE_FLEX_GAIN=-0.35
PRESSURE_RR_GAIN=0.60
PRESSURE_D_GAIN=0.0022
PRESSURE_IDEAL=28.0
FZ0=2800
DY_REF=1.47
DX_REF=1.425           ; Longitudinal grip
LS_EXPY=0.85         ; Lateral load sensitivity
LS_EXPX=0.89         ; Longitudinal load sensitivity
	;DY_CURVE=sx2_lat.lut ; removed
	;DX_CURVE=sx2_long.lut ; rempved
FALLOFF_LEVEL_CURVE=tire_heat_level.lut
FALLOFF_SPEED_CURVE=tire_heat_speed.lut
;FALLOFF_LEVEL=0.88
;FALLOFF_SPEED=7
	;DROPOFF_FACTOR_0=10.5
	;DROPOFF_FACTOR_1=1.00
	;FALLOFF_YSPEED_MULT=1.00

	;SAT_MULT=	1.1
	;SAT_SPEED=	1.2
	;SAT_PEAK_K=0.50
	;SAT_MULT_K=0.03
	;SAT_MIN_REF=0.03
	;SAT_LOAD_K=0.000010
SIDEWALL_K_MULT=	0.85 	; Multiplier for sidewall stiffness (affects flex & handling feel)
SIDEWALL_K_MULT_X=	1.2 	; Longitudinal sidewall stiffness multiplier
RADIUS_ANGULAR_K=	0.010 	; How much tire radius grows with wheel rotation speed (effective rolling radius)
RADIUS_ANGULAR_K_2=	0.02	; Secondary / higher speed effect on radius
ROLLING_RADIUS_MULT=	0.38	; Overall multiplier for rolling radius

; OLD deprecated
XMU=0.00
DY0=0.00
DY1=0.00
DX0=0.00
DX1=0.00
FLEX=0.00

[THERMAL_FRONT]
SURFACE_TRANSFER=0.95
PATCH_TRANSFER=0.0021
CORE_TRANSFER=0.00011
INTERNAL_CORE_TRANSFER=0.0015
FRICTION_K=0.0185
ROLLING_K=0.11
PERFORMANCE_CURVE=tire_heat_mu.lut
GRAIN_GAMMA=1.2
GRAIN_GAIN=0.13
BLISTER_GAMMA=1.2
BLISTER_GAIN=0.13
COOL_FACTOR=3.2
SURFACE_ROLLING_K=0.025
TREAD_DEPTH=0.0060
BULK_HEIGHT=10.8
BEAD_WIDTH=14.5

[THERMAL_REAR]
SURFACE_TRANSFER=0.95
PATCH_TRANSFER=0.0021
CORE_TRANSFER=0.00011
INTERNAL_CORE_TRANSFER=0.0015
FRICTION_K=0.0185
ROLLING_K=0.11
PERFORMANCE_CURVE=tire_heat_mu.lut
GRAIN_GAMMA=1.2
GRAIN_GAIN=0.13
BLISTER_GAMMA=1.2
BLISTER_GAIN=0.13
COOL_FACTOR=3.2
SURFACE_ROLLING_K=0.025
TREAD_DEPTH=0.0060
BULK_HEIGHT=10.8
BEAD_WIDTH=14.5

[THERMAL2_FRONT]
CARCASS_ROLLING_K=0.112
SURFACE_TO_AMBIENT=0.0305
SURFACE_TO_CARCASS=0.0475
CARCASS_TO_SURFACE=0.158
CARCASS_TO_CORE=0.0052
CORE_TO_CARCASS=0.0014
CORE_TO_AMBIENT=0.0020
BRAKE_TO_CORE=0.000032
FRICTION_TEMP_K=1.02

[THERMAL2_REAR]
CARCASS_ROLLING_K=0.112
SURFACE_TO_AMBIENT=0.0305
SURFACE_TO_CARCASS=0.0475
CARCASS_TO_SURFACE=0.158
CARCASS_TO_CORE=0.0052
CORE_TO_CARCASS=0.0014
CORE_TO_AMBIENT=0.0020
BRAKE_TO_CORE=0.000032
FRICTION_TEMP_K=1.02